import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
const cdp = await p.context().newCDPSession(p);
await cdp.send("Emulation.setEmulatedMedia", { features: [{ name: "pointer", value: "coarse" }, { name: "any-pointer", value: "coarse" }, { name: "hover", value: "none" }] });
await p.goto("http://localhost:3100/Market", { waitUntil: "domcontentloaded", timeout: 180000 });
const plot = p.locator("ol[aria-label^='Sets ordered'] > li").first().locator("[data-market-sparkline]");
await plot.waitFor({ timeout: 180000 });
await p.waitForTimeout(1500);
console.log("pointerMode", await plot.getAttribute("data-pointer-mode"));
await p.evaluate(() => { window.__ev = []; const el = document.querySelector("ol[aria-label^='Sets ordered'] [data-market-sparkline]"); for (const t of ["pointerdown","pointerup","pointermove","pointerleave","pointercancel","click"]) el.addEventListener(t, e => window.__ev.push(t + ":" + (e.pointerType||"")));});
const box = await plot.boundingBox();
console.log("box", JSON.stringify(box));
await p.touchscreen.tap(box.x + box.width * 0.5, box.y + box.height / 2);
await p.waitForTimeout(1200);
console.log("events", JSON.stringify(await p.evaluate(() => window.__ev)));
console.log("tooltips", await p.locator("[data-market-sparkline-tooltip]").count(), "url", p.url());
await b.close();
