BEGIN;

-- Phase 0 safety: suspend the legacy age-based prune before raw history
-- becomes old enough for this job to remove data needed by downstream rebuilds.
DO $$
DECLARE
    v_jobid bigint;
BEGIN
    SELECT jobid
      INTO v_jobid
      FROM cron.job
     WHERE jobname = 'prune-old-card-variant-price-observations'
        OR command = 'select public.prune_old_card_variant_price_observations(365);'
     ORDER BY jobid
     LIMIT 1;

    IF v_jobid IS NOT NULL THEN
        PERFORM cron.alter_job(v_jobid, active := false);
    END IF;
END
$$;

CREATE TABLE public.price_storage_v2_migration_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase text NOT NULL,
    captured_at timestamptz NOT NULL DEFAULT now(),
    database_size_bytes bigint,
    raw_observation_rows bigint,
    raw_observation_bytes bigint,
    interval_rows bigint,
    interval_bytes bigint,
    daily_state_rows bigint,
    daily_state_bytes bigint,
    monthly_rollup_rows bigint,
    monthly_rollup_bytes bigint,
    details jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE public.price_storage_v2_migration_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.price_storage_v2_migration_audit FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.price_storage_v2_migration_audit TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.price_storage_v2_migration_audit_id_seq TO service_role;

COMMENT ON TABLE public.price_storage_v2_migration_audit IS
'Backend-only audit trail for the additive Price Storage V2 migration. No production reader depends on this table.';

CREATE TABLE public.card_variant_price_events_v2 (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_variant_id uuid NOT NULL REFERENCES public.card_variants(id) ON DELETE CASCADE,
    condition_id uuid NOT NULL REFERENCES public.conditions(id),
    source text NOT NULL,
    currency text NOT NULL,
    effective_date date NOT NULL,
    event_type text NOT NULL,
    market_price numeric,
    high_price numeric,
    low_price numeric,
    source_observation_id uuid,
    source_created_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT card_variant_price_events_v2_event_type_check
      CHECK (event_type IN ('PRICE','UNPRICED','RETURNED_TO_MARKET','RETIRED')),
    CONSTRAINT card_variant_price_events_v2_price_state_check
      CHECK (
        (event_type IN ('PRICE','RETURNED_TO_MARKET') AND market_price IS NOT NULL)
        OR (event_type IN ('UNPRICED','RETIRED') AND market_price IS NULL)
      ),
    CONSTRAINT card_variant_price_events_v2_day_unique
      UNIQUE (card_variant_id, condition_id, source, currency, effective_date)
);

ALTER TABLE public.card_variant_price_events_v2 ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.card_variant_price_events_v2 FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.card_variant_price_events_v2 TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.card_variant_price_events_v2_id_seq TO service_role;

COMMENT ON TABLE public.card_variant_price_events_v2 IS
'Backend-only shadow history for Price Storage V2. Stores the first observed state and subsequent price-state changes; not yet a production authority.';

CREATE TABLE public.card_variant_price_current_v2 (
    card_variant_id uuid NOT NULL REFERENCES public.card_variants(id) ON DELETE CASCADE,
    condition_id uuid NOT NULL REFERENCES public.conditions(id),
    source text NOT NULL,
    currency text NOT NULL,
    event_id bigint NOT NULL REFERENCES public.card_variant_price_events_v2(id) ON DELETE CASCADE,
    effective_date date NOT NULL,
    state text NOT NULL,
    market_price numeric,
    high_price numeric,
    low_price numeric,
    source_observation_id uuid,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (card_variant_id, condition_id, source, currency),
    CONSTRAINT card_variant_price_current_v2_state_check
      CHECK (state IN ('PRICE','UNPRICED','RETURNED_TO_MARKET','RETIRED'))
);

ALTER TABLE public.card_variant_price_current_v2 ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.card_variant_price_current_v2 FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.card_variant_price_current_v2 TO service_role;

COMMENT ON TABLE public.card_variant_price_current_v2 IS
'Backend-only shadow latest-state projection for Price Storage V2; no existing production view points here yet.';

CREATE OR REPLACE FUNCTION public.rebuild_card_variant_price_events_v2_from_raw_scope(
    p_card_variant_ids uuid[]
)
RETURNS jsonb
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE
    v_event_rows bigint := 0;
    v_current_rows bigint := 0;
BEGIN
    IF p_card_variant_ids IS NULL OR cardinality(p_card_variant_ids) = 0 THEN
        RETURN jsonb_build_object('event_rows', 0, 'current_rows', 0, 'scope_variants', 0);
    END IF;

    DELETE FROM public.card_variant_price_current_v2 current_row
     WHERE current_row.card_variant_id = ANY(p_card_variant_ids);

    DELETE FROM public.card_variant_price_events_v2 event_row
     WHERE event_row.card_variant_id = ANY(p_card_variant_ids);

    WITH normalized AS MATERIALIZED (
        SELECT
            observation.id AS source_observation_id,
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN') AS source,
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD') AS currency,
            observation.captured_at AS effective_date,
            observation.market_price,
            observation.high_price,
            observation.low_price,
            observation.created_at AS source_created_at,
            lag(observation.market_price) OVER price_order AS previous_market_price,
            lag(observation.high_price) OVER price_order AS previous_high_price,
            lag(observation.low_price) OVER price_order AS previous_low_price,
            row_number() OVER price_order AS sequence_number
        FROM public.card_variant_price_observations observation
        WHERE observation.card_variant_id = ANY(p_card_variant_ids)
          AND observation.captured_at IS NOT NULL
        WINDOW price_order AS (
            PARTITION BY
                observation.card_variant_id,
                observation.condition_id,
                COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN'),
                COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD')
            ORDER BY observation.captured_at, observation.created_at, observation.id
        )
    ), change_events AS (
        SELECT *
          FROM normalized
         WHERE market_price IS NOT NULL
           AND (
                sequence_number = 1
                OR market_price IS DISTINCT FROM previous_market_price
                OR high_price IS DISTINCT FROM previous_high_price
                OR low_price IS DISTINCT FROM previous_low_price
           )
    )
    INSERT INTO public.card_variant_price_events_v2 (
        card_variant_id,
        condition_id,
        source,
        currency,
        effective_date,
        event_type,
        market_price,
        high_price,
        low_price,
        source_observation_id,
        source_created_at
    )
    SELECT
        card_variant_id,
        condition_id,
        source,
        currency,
        effective_date,
        'PRICE',
        market_price,
        high_price,
        low_price,
        source_observation_id,
        source_created_at
    FROM change_events
    ORDER BY card_variant_id, condition_id, source, currency, effective_date;

    GET DIAGNOSTICS v_event_rows = ROW_COUNT;

    WITH ranked AS (
        SELECT
            event_row.*,
            row_number() OVER (
                PARTITION BY event_row.card_variant_id, event_row.condition_id, event_row.source, event_row.currency
                ORDER BY event_row.effective_date DESC, event_row.id DESC
            ) AS latest_rank
        FROM public.card_variant_price_events_v2 event_row
        WHERE event_row.card_variant_id = ANY(p_card_variant_ids)
    )
    INSERT INTO public.card_variant_price_current_v2 (
        card_variant_id,
        condition_id,
        source,
        currency,
        event_id,
        effective_date,
        state,
        market_price,
        high_price,
        low_price,
        source_observation_id,
        updated_at
    )
    SELECT
        card_variant_id,
        condition_id,
        source,
        currency,
        id,
        effective_date,
        event_type,
        market_price,
        high_price,
        low_price,
        source_observation_id,
        now()
    FROM ranked
    WHERE latest_rank = 1;

    GET DIAGNOSTICS v_current_rows = ROW_COUNT;

    RETURN jsonb_build_object(
        'event_rows', v_event_rows,
        'current_rows', v_current_rows,
        'scope_variants', cardinality(p_card_variant_ids)
    );
END;
$$;

REVOKE ALL ON FUNCTION public.rebuild_card_variant_price_events_v2_from_raw_scope(uuid[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rebuild_card_variant_price_events_v2_from_raw_scope(uuid[]) TO service_role;

COMMENT ON FUNCTION public.rebuild_card_variant_price_events_v2_from_raw_scope(uuid[]) IS
'Shadow/backfill-only Price Storage V2 helper. Rebuilds only explicitly supplied variants from legacy raw observations; it is not the future append-only production writer.';

COMMIT;