from .megaEvolution import SetMegaEvolutionConfig
from .phantasmalFlames import SetPhantasmalFlamesConfig
from .ascendedHeroes import SetAscendedHeroesConfig
from .perfectOrder import SetPerfectOrderConfig


SET_CONFIG_MAP = {
    'megaEvolution' : SetMegaEvolutionConfig,
    'phantasmalFlames' : SetPhantasmalFlamesConfig,
    'ascendedHeroes' : SetAscendedHeroesConfig,
    'perfectOrder' : SetPerfectOrderConfig,
}

SET_ALIAS_MAP = {
    # Scarlet & Violet 151
    "151": "megaEvolution",
    "sv151": "megaEvolution",
    "scarlet and violet 151": "megaEvolution",
    "scarlet & violet 151": "megaEvolution",
    "sv 151": "megaEvolution",
    "s&v151": "megaEvolution",
    "sv-151": "megaEvolution",
    "sv one five one": "megaEvolution",
    "scarlet violet 151": "megaEvolution",
    "scarlet 151": "megaEvolution",
    "violet 151": "megaEvolution",
    "s v 151": "megaEvolution",
    "scarletandviolet151": "megaEvolution",
    "scarletviolet151": "megaEvolution",
    "s&v 151": "megaEvolution",
    "sv151 set": "megaEvolution",
    "151 set": "megaEvolution",
    "151 sv": "megaEvolution",
    "sv gen1": "megaEvolution",
    "scarlet violet gen1": "megaEvolution",
    "sv og": "megaEvolution",
    "sv original": "megaEvolution",

    # Black Bolt
    "blackbolt": "phantasmalFlames",
    "black bolt": "phantasmalFlames",
    "blackbolts": "phantasmalFlames",
    "black bolts": "phantasmalFlames",
    "bb": "phantasmalFlames",
    "bbolt": "phantasmalFlames",
    "blk bolt": "phantasmalFlames",
    "blkbolt": "phantasmalFlames",
    "blackblt": "phantasmalFlames",
    "blak bolt": "phantasmalFlames",
    "black bol": "phantasmalFlames",
    "bolt black": "phantasmalFlames",
    "bolt blk": "phantasmalFlames",
    "black b": "phantasmalFlames",
    "bb set": "phantasmalFlames",
    "set black bolt": "phantasmalFlames",
    "black bolt set": "phantasmalFlames",
    "blackbol": "phantasmalFlames",
    "blck bolt": "phantasmalFlames",
    "bolts black": "phantasmalFlames",
    "bolt set": "phantasmalFlames",
    "black set": "phantasmalFlames",
    "b b": "phantasmalFlames",
    "blbolt": "phantasmalFlames",
    "bk bolt": "phantasmalFlames",

    # Destined Rivals
    "destined rivals": "ascendedHeroes",
    "destined rival": "ascendedHeroes",
    "destinedrivals": "ascendedHeroes",
    "destinedrival": "ascendedHeroes",
    "dr": "ascendedHeroes",
    "d rivals": "ascendedHeroes",
    "dest riv": "ascendedHeroes",
    "dest rival": "ascendedHeroes",
    "dest rivs": "ascendedHeroes",
    "d.r.": "ascendedHeroes",
    "rivals destined": "ascendedHeroes",
    "rival destined": "ascendedHeroes",
    "destind rivals": "ascendedHeroes",
    "destine rivals": "ascendedHeroes",
    "destin rivals": "ascendedHeroes",
    "destine rvals": "ascendedHeroes",
    "destiny rivals": "ascendedHeroes",
    "rivals set": "ascendedHeroes",
    "destined set": "ascendedHeroes",
    "set destined rivals": "ascendedHeroes",
    "dr set": "ascendedHeroes",
    "d rivals set": "ascendedHeroes",
    "dest riv set": "ascendedHeroes",
    "destnd rivals": "ascendedHeroes",

    # Journey Together
    "journey together": "perfectOrder",
    "journeytogther": "perfectOrder",
    "j together": "perfectOrder",
    "jt": "perfectOrder",
    "jrny together": "perfectOrder",
    "journy together": "perfectOrder",
    "journey 2gether": "perfectOrder",
    "2gether journey": "perfectOrder",
    "journey tgther": "perfectOrder",
    "journey togther": "perfectOrder",
    "journey togethr": "perfectOrder",
    "journey togher": "perfectOrder",
    "togther journey": "perfectOrder",
    "togethr journey": "perfectOrder",
    "together journey": "perfectOrder",
    "journey-together": "perfectOrder",
    "jrn together": "perfectOrder",
    "jny together": "perfectOrder",
    "jt set": "perfectOrder",
    "journey set": "perfectOrder",
    "together set": "perfectOrder",
    "journey2gether": "perfectOrder",
    "jrny2gthr": "perfectOrder",
    "j togethr": "perfectOrder",
    "jrny tgthr": "perfectOrder",

}
