BEGIN; SET LOCAL statement_timeout='12s'; SET LOCAL lock_timeout='1s';
DO $test$
DECLARE r uuid; n uuid; s jsonb; x jsonb; ver integer; rejected boolean; tests jsonb:='[]';
BEGIN
 SELECT id INTO STRICT r FROM public.sets WHERE canonical_key='hiddenFates';
 s:=public.stage_pokemon_market_basket_v3(r,'standard','rollback-v3-hidden-membership-tests','Rollback-only test that positive partial parent values do not bypass basket membership.'); ver:=(s->>'basketVersion')::integer;
 IF (s->>'expectedCards')::integer<>163 OR (s->>'expectedMembers')::integer<>2 OR (s->'resolutionCounts'->>'BOUND')::integer<>163 THEN RAISE EXCEPTION 'TESTFAIL: intended Hidden Fates roster differs'; END IF;
 tests:=tests||jsonb_build_array('hidden_fates_includes_69_plus_94_cards');
 rejected:=false;
 BEGIN
  DELETE FROM public.pokemon_market_basket_bindings_v3 WHERE root_set_id=r AND market_scope='standard' AND basket_version=ver AND member_set_id<>r;
  DELETE FROM public.pokemon_market_basket_members_v3 WHERE root_set_id=r AND market_scope='standard' AND basket_version=ver AND member_set_id<>r;
  PERFORM public.approve_pokemon_market_basket_v3(r,'standard',ver,s->>'catalogFingerprint',public.pokemon_market_binding_fingerprint_v3(r,'standard',ver),'Must reject the real incident: drop Shiny Vault while the parent remains positive.');
 EXCEPTION WHEN raise_exception THEN IF SQLERRM NOT LIKE 'V3 approval requires every intended card%' THEN RAISE; END IF; rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'TESTFAIL: omitted entire Shiny Vault approved'; END IF;
 tests:=tests||jsonb_build_array('omitted_counted_subset_rejects_even_with_remaining_parent');
 rejected:=false;
 BEGIN
  DELETE FROM public.pokemon_market_basket_bindings_v3 WHERE root_set_id=r AND market_scope='standard' AND basket_version=ver AND canonical_card_id=(SELECT canonical_card_id FROM public.pokemon_market_basket_bindings_v3 WHERE root_set_id=r AND market_scope='standard' AND basket_version=ver LIMIT 1);
  PERFORM public.approve_pokemon_market_basket_v3(r,'standard',ver,s->>'catalogFingerprint',public.pokemon_market_binding_fingerprint_v3(r,'standard',ver),'Must reject one missing slot rather than reducing the expected-card denominator.');
 EXCEPTION WHEN raise_exception THEN IF SQLERRM NOT LIKE 'V3 approval requires every intended card%' THEN RAISE; END IF; rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'TESTFAIL: missing single expected card approved'; END IF;
 tests:=tests||jsonb_build_array('single_missing_slot_rejects');
 rejected:=false;
 BEGIN UPDATE public.pokemon_market_basket_versions_v3 SET expected_card_count=69 WHERE root_set_id=r AND market_scope='standard' AND basket_version=ver;
 EXCEPTION WHEN raise_exception THEN IF SQLERRM NOT LIKE 'V3 draft definition identity cannot change%' THEN RAISE; END IF; rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'TESTFAIL: expectation reduced to fit partial data'; END IF;
 tests:=tests||jsonb_build_array('shrinking_expected_count_rejects');
 rejected:=false;
 BEGIN UPDATE public.pokemon_market_basket_versions_v3 SET effective_from=effective_from-1 WHERE root_set_id=r AND market_scope='standard' AND basket_version=ver;
 EXCEPTION WHEN raise_exception THEN IF SQLERRM NOT LIKE 'V3 draft definition identity cannot change%' THEN RAISE; END IF; rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'TESTFAIL: silently backdated current definition'; END IF;
 tests:=tests||jsonb_build_array('silent_definition_backdating_rejects');
 SELECT id INTO STRICT n FROM public.sets WHERE canonical_key='neoDestiny';
 x:=public.inspect_pokemon_market_basket_v3(n,'first_edition',1);rejected:=false;
 BEGIN PERFORM public.approve_pokemon_market_basket_v3(n,'first_edition',1,x->>'catalogFingerprint',x->>'bindingFingerprint','Must reject unresolved First Edition card rather than use Unlimited.');
 EXCEPTION WHEN raise_exception THEN IF SQLERRM NOT LIKE 'V3 approval requires every intended card%' THEN RAISE; END IF; rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'TESTFAIL: unresolved edition basket approved'; END IF;
 tests:=tests||jsonb_build_array('unresolved_exact_edition_keeps_definition_unapproved');
 rejected:=false;
 BEGIN EXECUTE 'SET LOCAL ROLE service_role'; UPDATE public.pokemon_market_basket_bindings_v3 SET candidate_count=1 WHERE false;
 EXCEPTION WHEN insufficient_privilege THEN rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'TESTFAIL: service role can bypass controlled writes'; END IF;
 tests:=tests||jsonb_build_array('service_role_direct_dml_denied');
 rejected:=false;
 BEGIN EXECUTE 'SET LOCAL ROLE service_role'; PERFORM public.approve_pokemon_market_basket_v3(r,'standard',ver,s->>'catalogFingerprint',s->>'bindingFingerprint','Application credentials cannot approve new economic basket definitions.');
 EXCEPTION WHEN insufficient_privilege THEN rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'TESTFAIL: application credentials can approve definitions'; END IF;
 tests:=tests||jsonb_build_array('service_role_definition_approval_denied');
 rejected:=false;
 BEGIN EXECUTE 'SET LOCAL ROLE anon'; PERFORM public.inspect_pokemon_market_basket_v3(r,'standard',ver);
 EXCEPTION WHEN insufficient_privilege THEN rejected:=true; END;
 IF NOT rejected THEN RAISE EXCEPTION 'TESTFAIL: anon can execute internal inspector'; END IF;
 tests:=tests||jsonb_build_array('anonymous_internal_function_denied');
 EXECUTE 'SET LOCAL ROLE service_role';x:=public.inspect_pokemon_market_basket_v3(r,'standard',ver);EXECUTE 'RESET ROLE';
 IF (x->>'expectedCards')::integer<>163 THEN RAISE EXCEPTION 'TESTFAIL: authorized read inspector failed'; END IF;
 tests:=tests||jsonb_build_array('service_role_read_inspection_allowed');
 IF public.pokemon_market_binding_fingerprint_v3(r,'standard',ver)<>s->>'bindingFingerprint' THEN RAISE EXCEPTION 'TESTFAIL: failed mutations escaped their rollback boundaries'; END IF;
 tests:=tests||jsonb_build_array('failed_mutations_preserved_complete_original_definition');
 PERFORM set_config('market_v3.test_receipt',jsonb_build_object('passed',jsonb_array_length(tests),'tests',tests,'all_changes_rolled_back',true)::text,true);
END $test$;
SELECT current_setting('market_v3.test_receipt')::jsonb AS validation; ROLLBACK;
