"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import CollectorAppealBreakdown from "@/components/explore/CollectorAppealBreakdown";
import FinancialRipV3Breakdown from "@/components/explore/FinancialRipV3Breakdown";
import RipDistributionChart from "@/components/explore/RipDistributionChart";
import { readCanonicalBlock, resolveCanonicalRipV7 } from "@/components/explore/canonicalRipV7.mjs";
import { getRipPageIconPresentation } from "@/components/explore/ripPageIconPresentation.mjs";
import SetPageIcon from "@/components/pokemon/set-page/SetPageIcon";
import RankBadge from "@/components/ui/RankBadge";
import { formatPublicRipScore } from "@/constants/exploreRankingConfig";
import { getPokemonSetInsightsCritical } from "@/lib/pokemon/pokemonSetInsightsCriticalClient";
import { getPokemonSetInsightsSecondary } from "@/lib/pokemon/pokemonSetInsightsSecondaryClient";
import { buildTcgSetHrefFromTarget } from "@/lib/explore/ripStatisticsRouting";

const SECTIONS = [["overview","Overview","gauge"],["simulation","Simulation","analysis"],["financial-rip","Financial RIP","shield"],["collector-appeal","Collector Appeal","star"],["market-context","Market Context","trend"]];
function number(value) { const parsed=Number(value); return value===null||value===undefined||value===""||!Number.isFinite(parsed)?null:parsed; }
function money(value) { const parsed=number(value); return parsed===null?"—":parsed.toLocaleString("en-US",{style:"currency",currency:"USD"}); }
function probability(value) { const parsed=number(value); if(parsed===null)return "—"; const percent=parsed<=1?parsed*100:parsed; return `${percent.toFixed(1).replace(/\.0$/,"")}%`; }
function multiple(value) { const parsed=number(value); return parsed===null?"—":`${parsed.toFixed(2).replace(/0+$/,"").replace(/\.$/,"")}×`; }
function percentile(rows,wanted) { const match=(Array.isArray(rows)?rows:[]).find((row)=>number(row?.percentile??row?.p??row?.quantile)===wanted); return number(match?.value??match?.packValue??match?.pack_value); }

function SectionHeading({eyebrow,icon,title,description,id}) { return <div className="min-w-0">{eyebrow?<p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[var(--text-secondary)]">{eyebrow}</p>:null}<h2 id={id} className="mt-1 flex items-center gap-2.5 text-xl font-semibold text-[var(--text-primary)]">{icon?<SetPageIcon name={icon} className="h-4 w-4 text-[var(--accent)]"/>:null}{title}</h2>{description?<p className="mt-1 max-w-3xl text-sm leading-relaxed text-[var(--text-secondary)]">{description}</p>:null}</div>; }

function ScoreCard({label,icon,role,block,primary=false}) {
  const metric=readCanonicalBlock(block); const presentation=getRipPageIconPresentation(role,metric.tier); const score=number(metric.publicScore); const rank=metric.rank===null?"Rank unavailable":`#${Math.round(metric.rank)}${metric.cohortSize===null?"":` of ${Math.round(metric.cohortSize)}`}`;
  return <div data-analysis-score={role} className={`min-w-0 rounded-xl border border-[var(--border-subtle)] bg-[rgba(2,8,23,0.36)] p-4 ${primary?"md:p-5":""}`}><div className="flex min-w-0 items-center justify-between gap-3"><span className="flex min-w-0 items-center gap-2 text-xs font-semibold uppercase tracking-[0.07em] text-[var(--text-primary)]"><SetPageIcon name={icon} className="h-3.5 w-3.5" style={presentation.style}/>{label}</span>{metric.tier?<RankBadge rank={metric.tier} format="tier" size="compact" subtle/>:null}</div><div className="mt-5 flex items-baseline gap-1"><span className={`${primary?"text-[2rem]":"text-3xl"} font-semibold leading-none tabular-nums text-[var(--text-primary)]`}>{score===null?"—":formatPublicRipScore(score)}</span>{score===null?null:<span className="text-xs font-medium text-[var(--text-secondary)]">/10</span>}</div><p className="mt-3 text-xs tabular-nums text-[var(--text-secondary)]">{rank}</p><div className="mt-4 flex items-center gap-2"><span className="h-1.5 min-w-0 flex-1 overflow-hidden rounded-full bg-[var(--border-subtle)]" role="progressbar" aria-label={`${label} score`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={score??undefined}>{score===null?null:<span className="block h-full rounded-full" style={{width:`${Math.max(0,Math.min(100,score))}%`,backgroundColor:presentation.style.color}}/>}</span></div></div>;
}

function MetricGrid({rows}) { const visible=rows.filter((row)=>row.value!=="—"); if(!visible.length)return <p className="mt-4 text-sm text-[var(--text-secondary)]">No additional published metrics are available for this section.</p>; return <dl className="mt-4 grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-[var(--border-subtle)] bg-[var(--border-subtle)] lg:grid-cols-4">{visible.map((row)=><div key={row.label} className="min-w-0 bg-[var(--surface-panel)] p-3"><dt className="text-[10px] font-semibold uppercase tracking-[0.08em] text-[var(--text-secondary)]">{row.label}</dt><dd className="mt-1 text-lg font-semibold tabular-nums text-[var(--text-primary)]">{row.value}</dd>{row.helper?<dd className="mt-0.5 text-[11px] text-[var(--text-secondary)]">{row.helper}</dd>:null}</div>)}</dl>; }

export default function PokemonSetAnalysisClient({selectedTarget,targets=[]}) {
  const router=useRouter(); const searchParams=useSearchParams(); const requestedSection=String(searchParams.get("section")||"overview").toLowerCase(); const activeSection=SECTIONS.some(([value])=>value===requestedSection)?requestedSection:"overview";
  const [critical,setCritical]=useState(null); const [secondary,setSecondary]=useState(null); const [error,setError]=useState(null); const setId=selectedTarget?.target_id; const setName=selectedTarget?.name||"this set"; const setHref=buildTcgSetHrefFromTarget(selectedTarget);
  useEffect(()=>{let current=true;setCritical(null);setSecondary(null);setError(null);Promise.all([getPokemonSetInsightsCritical(setId),getPokemonSetInsightsSecondary(setId)]).then(([nextCritical,nextSecondary])=>{if(current){setCritical(nextCritical);setSecondary(nextSecondary);}}).catch((reason)=>{if(current)setError(reason?.message||"Analysis is unavailable.");});return()=>{current=false;};},[setId]);
  const canonical=useMemo(()=>resolveCanonicalRipV7(critical),[critical]); const summary=critical?.summary||secondary?.ripStatistics?.summary||secondary?.ripStatistics||{}; const percentiles=secondary?.outcomeDistribution?.percentiles||[]; const distributionBins=secondary?.outcomeDistribution?.distributionBins||[]; const thresholdBins=secondary?.outcomeDistribution?.thresholdBins||[]; const sectionHref=(section)=>`?section=${section}`;
  const p25=percentile(percentiles,25),p50=percentile(percentiles,50)??number(summary.median_value),p75=percentile(percentiles,75),p95=percentile(percentiles,95),p99=percentile(percentiles,99);
  const switchSet=(event)=>{const target=targets.find((row)=>String(row.target_id)===event.target.value);const href=target?buildTcgSetHrefFromTarget(target):null;if(href)router.push(`${href}/analysis?section=${activeSection}`);};
  const metricRows=(rows)=>rows.map(([label,value,helper])=>({label,value,helper}));

  return <main data-analysis-page className="w-full max-w-full pb-[calc(5.25rem+env(safe-area-inset-bottom)+0.875rem)] pt-0 desk:pb-8 desk:pt-8"><div className="mx-auto w-full max-w-[960px] desk:max-w-[1440px] desk:px-4 2xl:px-5"><div className="set-detail-glass-scope mx-auto flex w-full max-w-[1400px] min-w-0 flex-col px-4 pt-3 sm:px-5 desk:px-0 desk:pt-0">
    <Link href={setHref} className="mb-2 inline-flex min-h-11 w-fit items-center gap-2 rounded-lg px-1 text-sm font-medium text-[var(--text-secondary)] transition-colors hover:text-[var(--text-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]"><span aria-hidden="true">←</span> Back to Set</Link>
    <header className="set-glass-surface overflow-hidden rounded-2xl border p-4 sm:p-5 desk:p-6"><div className="grid gap-5 desk:grid-cols-[minmax(0,1fr)_minmax(15rem,22rem)] desk:items-end"><div className="min-w-0"><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-purple-300"><SetPageIcon name="analysis" className="h-3.5 w-3.5"/>Analysis</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-[var(--text-primary)] sm:text-3xl">Deep Dive Analysis</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[var(--text-secondary)] sm:text-base">Understand why {setName} ranks the way it does.</p></div><label className="block min-w-0 text-[10px] font-semibold uppercase tracking-[0.1em] text-[var(--text-secondary)]">Current Set<select value={String(setId)} onChange={switchSet} className="mt-2 min-h-11 w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-page)] px-3 text-sm font-semibold normal-case tracking-normal text-[var(--text-primary)] shadow-[inset_0_1px_0_rgba(255,255,255,0.04)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)]">{targets.map((target)=><option key={target.target_id} value={target.target_id}>{target.name}</option>)}</select></label></div></header>
    <nav aria-label="Analysis sections" className="set-detail-sticky-tabs sticky top-[var(--app-header-offset,64px)] z-20 mt-2 overflow-x-auto rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-panel)] p-1 shadow-[0_8px_24px_rgba(2,6,23,0.24)] [scrollbar-width:none] desk:static desk:rounded-2xl"><div className="flex min-w-max items-center gap-0.5 rounded-lg border border-[rgba(255,255,255,0.08)] bg-[rgba(2,6,23,0.72)] p-0.5 shadow-[inset_0_1px_0_rgba(255,255,255,0.04),0_8px_20px_rgba(2,6,23,0.18)] desk:grid desk:min-w-0 desk:grid-cols-5">{SECTIONS.map(([value,label,icon])=>{const selected=activeSection===value;return <Link key={value} href={sectionHref(value)} aria-current={selected?"page":undefined} className={`inline-flex min-h-12 min-w-max items-center justify-center gap-1.5 rounded-md px-3 py-1 text-[13px] font-semibold leading-none transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)] desk:min-h-0 desk:min-w-0 desk:px-2 desk:py-2 desk:text-xs ${selected?"bg-[linear-gradient(135deg,rgba(124,58,237,0.88),rgba(109,40,217,0.72))] text-white shadow-[0_4px_12px_rgba(109,40,217,0.2),inset_0_1px_0_rgba(255,255,255,0.14)]":"bg-transparent text-[color:color-mix(in_srgb,var(--text-secondary)_82%,transparent)] hover:bg-[rgba(255,255,255,0.045)] hover:text-[var(--text-primary)]"}`}><SetPageIcon name={icon} className="h-3.5 w-3.5 flex-none"/><span className="whitespace-nowrap">{label}</span></Link>;})}</div></nav>
    {error?<p className="mt-4 rounded-xl border border-red-400/30 bg-[var(--surface-panel)] p-4 text-sm text-red-300">{error}</p>:null}{!critical&&!error?<p className="mt-4 rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-panel)] p-5 text-sm text-[var(--text-secondary)]">Loading canonical analysis…</p>:null}
    {critical?<div className="mt-4 min-w-0">
      {activeSection==="overview"?<section aria-labelledby="analysis-overview-title" className="space-y-4"><article className="set-glass-surface rounded-2xl border p-4 sm:p-5"><SectionHeading eyebrow="Why it ranks" icon="analysis" id="analysis-overview-title" title={`Why ${setName} ranks ${readCanonicalBlock(canonical.overall).rank===null?"where it does":`#${Math.round(readCanonicalBlock(canonical.overall).rank)}`}`} description="The published Overall RIP, Financial RIP, and Collector Appeal results behind this set’s position."/><div className="mt-4 grid gap-3 md:grid-cols-3"><ScoreCard label="Overall RIP" icon="gauge" role="overall" block={canonical.overall} primary/><ScoreCard label="Financial RIP" icon="shield" role="financial" block={canonical.financialRip}/><ScoreCard label="Collector Appeal" icon="star" role="collector" block={canonical.collectorAppeal}/></div></article><article className="set-glass-surface rounded-2xl border p-4 sm:p-5"><SectionHeading icon="bulb" title="How to read this result" description="Overall RIP is the canonical combined result. The supporting scores remain separate so unavailable inputs are visible instead of being filled with estimates."/><nav aria-label="Explore score details" className="mt-4 flex flex-col gap-2 sm:flex-row"><Link href={sectionHref("financial-rip")} className="inline-flex min-h-11 items-center justify-center rounded-lg border border-[var(--border-subtle)] px-3 text-sm font-semibold text-[var(--accent)]">View Financial RIP details →</Link><Link href={sectionHref("collector-appeal")} className="inline-flex min-h-11 items-center justify-center rounded-lg border border-[var(--border-subtle)] px-3 text-sm font-semibold text-[var(--accent)]">View Collector Appeal details →</Link></nav></article></section>:null}
      {activeSection==="simulation"?<section aria-labelledby="analysis-simulation-title" className="space-y-4"><article className="set-glass-surface min-w-0 rounded-2xl border p-4 sm:p-5"><SectionHeading eyebrow="Modeled outcomes" icon="analysis" id="analysis-simulation-title" title="What Do the Simulated Openings Actually Look Like?" description="The familiar opening summary first, followed by the published distribution and deeper outcome bands."/><MetricGrid rows={metricRows([["Expected Value",money(summary.mean_value),"long-run mean"],["Typical Opening",money(p50),"P50 / median"],["Strong Upside",money(p95),"P95 threshold"],["Jackpot Upside",money(p99),"top-1% threshold"]])}/><div className="mt-4 min-w-0">{distributionBins.length||thresholdBins.length?<RipDistributionChart bins={distributionBins} thresholdBins={thresholdBins} showTitle={false} flush/>:<div className="rounded-xl border border-dashed border-[var(--border-subtle)] bg-[var(--surface-page)]/40 px-4 py-4"><p className="text-sm font-medium text-[var(--text-primary)]">Distribution unavailable</p><p className="mt-1 text-xs leading-relaxed text-[var(--text-secondary)]">This set’s published simulation snapshot does not currently include the full outcome distribution.</p></div>}</div></article><article className="set-glass-surface rounded-2xl border p-4 sm:p-5"><SectionHeading title="Typical outcomes" description="Published percentile thresholds around the middle of the modeled opening distribution."/><MetricGrid rows={metricRows([["P25",money(p25),"25th percentile"],["P50",money(p50),"median"],["P75",money(p75),"75th percentile"]])}/></article><div className="grid gap-4 lg:grid-cols-2"><article className="set-glass-surface rounded-2xl border p-4 sm:p-5"><SectionHeading title="Downside" description="Published loss and pack-cost recovery measures."/><MetricGrid rows={metricRows([["Chance to Recover Cost",probability(summary.prob_profit??summary.chance_to_beat_pack_cost),null],["Expected Loss / Pack",money(summary.expected_loss_per_pack),null],["Loss When Losing",money(summary.expected_loss_when_losing),null]])}/></article><article className="set-glass-surface rounded-2xl border p-4 sm:p-5"><SectionHeading title="Upside" description="Published high-end outcome thresholds and their relationship to pack cost."/><MetricGrid rows={metricRows([["P95",money(p95),"strong upside"],["P99",money(p99),"top 1%"],["P95 / Cost",multiple(summary.p95_value_to_cost_ratio),null],["P99 / Cost",multiple(summary.p99_value_to_cost_ratio),null]])}/></article></div></section>:null}
      {activeSection==="financial-rip"?<section aria-labelledby="analysis-financial-title" className="set-glass-surface rounded-2xl border p-4 sm:p-5"><SectionHeading eyebrow="Opening economics" icon="shield" id="analysis-financial-title" title="Financial RIP" description="The six canonical opening-economics factors, using the same disclosure cards, ranks, tiers, and score rails as the Set experience."/><div className="mt-4 border-t border-[var(--border-subtle)] pt-4"><FinancialRipV3Breakdown canonical={canonical}/></div></section>:null}
      {activeSection==="collector-appeal"?<section aria-labelledby="analysis-collector-title" className="set-glass-surface rounded-2xl border p-4 sm:p-5"><SectionHeading eyebrow="Collector profile" icon="star" id="analysis-collector-title" title="Collector Appeal" description="Published production factors only. If the canonical contract does not publish a score or component, it remains explicitly unavailable."/><div className="mt-4 border-t border-[var(--border-subtle)] pt-4"><CollectorAppealBreakdown canonical={canonical}/></div><Link href="/Articles/how-collector-appeal-works" className="mt-4 inline-flex min-h-11 items-center text-sm font-semibold text-[var(--accent)]">Read the Collector Appeal methodology →</Link></section>:null}
      {activeSection==="market-context"?<section aria-labelledby="analysis-market-title" className="set-glass-surface rounded-2xl border p-4 sm:p-5"><SectionHeading eyebrow="Current context" icon="trend" id="analysis-market-title" title="Market Context" description="The live market input available in this analysis snapshot, kept compact so this page does not duplicate the full Market experience."/><dl className="mt-4 max-w-md border-y border-[var(--border-subtle)]"><div className="flex items-baseline justify-between gap-4 py-4"><dt className="text-sm text-[var(--text-secondary)]">Current pack price</dt><dd className="text-xl font-semibold tabular-nums text-[var(--text-primary)]">{money(summary.pack_cost)}</dd></div></dl><Link href={`${setHref}?tab=market`} className="mt-4 inline-flex min-h-11 items-center font-semibold text-[var(--accent)]">View full Market →</Link></section>:null}
    </div>:null}
    <footer className="mt-6 border-t border-[var(--border-subtle)] py-5"><Link href={setHref} className="inline-flex min-h-11 items-center font-semibold text-[var(--accent)]">Return to {setName} RIP →</Link></footer>
  </div></div></main>;
}
