import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
const products = fs.readFileSync(new URL("./RankingsProductLensClient.jsx", import.meta.url), "utf8");
const presentation = fs.readFileSync(new URL("./productRankingsPresentation.mjs", import.meta.url), "utf8");
const details = fs.readFileSync(new URL("./BestOpenDetailsPopover.jsx", import.meta.url), "utf8");
const productRip = fs.readFileSync(new URL("../pokemon/sealed-product-detail/ProductRipSection.jsx", import.meta.url), "utf8");
test("Best-Open has a dedicated Product Economics column", () => { assert.match(products, /bestOpenPrice: "Best-Open Price"/); assert.match(products, /<BestOpenDetailsPopover row=\{row\}/); assert.match(presentation, /bestOpenPriceGapDollars/); assert.match(presentation, /bestOpenPriceGapPercent/); });
test("Best-Open is loaded only through the paid lazy Economics authority", () => { assert.match(products, /readProductRankings\(view/); assert.match(products, /publicMode \? await readPublicProductCatalogue/); assert.match(products, /value: "economics"/); });
test("freshness and gaps use semantic popover copy without raw status enums", () => { assert.match(details, /Best-Open:/); assert.match(details, /independently dated/); assert.match(products, /BestOpenDetailsPopover/); assert.doesNotMatch(details, /resolved_below_market|current_number_one_with_headroom/); });
test("Product detail remains unchanged", () => { assert.doesNotMatch(productRip, /Best-Open|bestOpenPrice/); });
