"use client";
import { useState } from "react";
import BenchmarkScoreBadge from "./BenchmarkScoreBadge";
import { benchmarkMetric } from "./ripBenchmarkPresentation.mjs";
import AnalyticsTableShell from "./AnalyticsTableShell";
import styles from "./explore.module.css";
const METRICS = ["financial", "chase", "collector"];
export default function EraRankings({ contract, benchmark, onSelectEra }) {
  const [query, setQuery] = useState(""); const needle = query.trim().toLowerCase();
  const rows = (contract?.eras || []).map((era) => ({ era, overall: benchmarkMetric(benchmark?.rows, "era", era.eraId, "overall") })).filter(({ era }) => !needle || String(era.eraName).toLowerCase().includes(needle)).sort((a, b) => a.overall.rank == null ? 1 : b.overall.rank == null ? -1 : a.overall.rank - b.overall.rank);
  if (!contract || !rows.length) return <section className={`${styles.surface} rounded-xl p-5`}><h2 className="font-semibold">Era RIP Score unavailable</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">The certified Era Benchmark contract is temporarily unavailable.</p></section>;
  return <AnalyticsTableShell title="Best Eras to Rip Right Now" info="Era RIP Score is the backend-certified equal-set mean of canonical member Set Overall raw scores. Scores are benchmark-centered; rank is canonical and independent." query={query} onQueryChange={(event) => setQuery(event.target.value)} searchPlaceholder="Search eras..." searchLabel="Search eras" context="Select an era to view its modeled sets." shown={rows.length} ranked={rows[0]?.overall?.cohortSize || rows.length} marketDate={benchmark?.freshness?.benchmarkMarketDate || null}>
    <section data-era-rankings><div className="hidden overflow-x-auto desk:block"><table className={styles.table}><thead className={styles.head}><tr><th>Rank</th><th>Era</th><th>Era RIP Score</th>{METRICS.map((metric) => <th key={metric}>{metric[0].toUpperCase() + metric.slice(1)}</th>)}<th>Modeled Sets</th></tr></thead><tbody>{rows.map(({ era, overall }) => <tr className={styles.row} key={era.eraId}><td>#{overall.rank}</td><td><button className="font-semibold hover:underline" onClick={() => onSelectEra?.(era)}>{era.eraName}</button></td><td><BenchmarkScoreBadge metric={overall} label="Era RIP Score" /></td>{METRICS.map((key) => <td key={key}><BenchmarkScoreBadge metric={benchmarkMetric(benchmark?.rows, "era", era.eraId, key)} compact label={`${key} RIP Score`} /></td>)}<td>{era.modeledSetCount}</td></tr>)}</tbody></table></div><ul className="space-y-2.5 p-3 desk:hidden">{rows.map(({ era, overall }) => <li key={era.eraId} className={`${styles.surfaceQuiet} rounded-xl p-4`}><div className="flex justify-between gap-3"><button className="font-semibold hover:underline" onClick={() => onSelectEra?.(era)}>{era.eraName}</button><BenchmarkScoreBadge metric={overall} compact label="Era RIP Score" /></div><p className="mt-2 text-xs text-[var(--text-secondary)]">{era.modeledSetCount} modeled sets</p><div className="mt-2 grid grid-cols-3 gap-2">{METRICS.map((key) => <BenchmarkScoreBadge key={key} metric={benchmarkMetric(benchmark?.rows, "era", era.eraId, key)} compact label={`${key} RIP Score`} />)}</div></li>)}</ul></section>
  </AnalyticsTableShell>;
}
