import { eraStrengthRows, displayScore } from "./eraSetStrengthSelector.mjs";
import { RipScoreBadge, RipTierMark } from "./RipScoreBadge.jsx";
import styles from "./explore.module.css";

export default function EraRankings({ contract, onSelectEra }) {
  const rows = eraStrengthRows(contract);
  return <section data-era-rankings>
    <header className="mb-3"><h2 className="text-lg font-semibold text-[var(--text-primary)]">Era Set Strength</h2><p className="text-xs text-[var(--text-secondary)]">Equal-weight average of each era&apos;s canonical Set RIP scores. Opening economics do not affect this ranking.</p></header>
    <div className={`${styles.surface} hidden overflow-x-auto desk:block`}><table className={styles.table}><thead className={styles.head}><tr><th>Rank</th><th>Era</th><th>Score</th><th>Tier</th><th>Sets</th><th>Strongest set</th><th>Constituent Set RIP</th></tr></thead><tbody>{rows.map((era) => <tr key={era.eraId || era.eraName}><td>{era.rank ? `#${era.rank} of ${era.cohortSize}` : "—"}</td><th className="text-left"><button className="font-semibold hover:underline" onClick={() => onSelectEra?.(era)}>{era.eraName}</button></th><td><RipScoreBadge score={era.score} tier={era.tier}/></td><td><RipTierMark tier={era.tier}/></td><td>{era.modeledSetCount}</td><td>{era.strongestSet?.setName || "—"}</td><td><div className="flex min-w-40 items-center gap-1" aria-label={`${era.eraName} constituent Set RIP scores`}>{(era.constituentSets || []).map(set => <span key={set.setId} title={`${set.setName}: ${displayScore(Number(set.score) / 10) || "Unavailable"}`} className="h-2.5 w-2.5 rotate-45 border border-[rgb(var(--ex-teal))]" style={{opacity: set.score == null ? .2 : .35 + Number(set.score) / 155}} />)}</div></td></tr>)}</tbody></table></div>
    <ul className="space-y-2.5 desk:hidden">{rows.map(era => <li key={era.eraId || era.eraName} className={`${styles.surface} rounded-xl p-4`}><div className="flex items-start justify-between"><div><span className="text-xs text-[var(--text-secondary)]">{era.rank ? `#${era.rank} of ${era.cohortSize}` : "Unranked"}</span><button className="block text-left font-semibold hover:underline" onClick={() => onSelectEra?.(era)}>{era.eraName}</button></div><div className="flex gap-2"><RipScoreBadge score={era.score} tier={era.tier}/><RipTierMark tier={era.tier}/></div></div><p className="mt-3 text-xs text-[var(--text-secondary)]">{era.modeledSetCount} modeled sets · strongest: <span className="text-[var(--text-primary)]">{era.strongestSet?.setName || "Unavailable"}</span></p></li>)}</ul>
  </section>;
}
