"use client";

import { formatEvRepPacks, formatEvRepPercent } from "./evRepresentativenessSelector.mjs";

export default function EvRealizationCard({ horizon = null, entitled = false, context = "set" }) {
  const available = entitled && horizon;
  const productContext = context === "product";
  return <section data-ev-realization-card data-ev-realization-state={available ? "available" : entitled ? "unavailable" : "locked"} className="relative overflow-hidden rounded-2xl border border-[color-mix(in_srgb,var(--accent)_28%,var(--border-subtle))] bg-[linear-gradient(145deg,rgba(15,23,42,.82),rgba(2,8,23,.58))] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,.06),0_18px_45px_rgba(0,0,0,.18)]">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[var(--accent)]">EV Realization</p><p className="mt-1 text-xs text-[var(--text-secondary)]">{productContext ? "Underlying set metric · not recalculated for this product" : "How quickly modeled openings approach the set's long-run EV"}</p></div>{productContext ? <span className="rounded-full border border-[var(--border-subtle)] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.08em] text-[var(--text-secondary)]">Parent set</span> : null}</div>
    {available ? <><p className="mt-5 text-4xl font-semibold leading-none tabular-nums text-[var(--text-primary)]">~{formatEvRepPacks(horizon.packCount)}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--text-secondary)]">About <strong className="text-[var(--text-primary)]">{formatEvRepPercent(horizon.openerProbability)}</strong> of modeled openers reach at least <strong className="text-[var(--text-primary)]">{formatEvRepPercent(horizon.targetEvRatio)}</strong> of this set&apos;s long-run EV by this point.</p><div data-ev-realization-timeline className="relative mt-6 grid grid-cols-3 text-center"><span className="absolute left-[10%] right-[10%] top-2 h-px bg-[linear-gradient(90deg,rgba(45,212,191,.3),rgba(45,212,191,.95))]" />{[["Start", "1 pack"], ["Milestone", `~${formatEvRepPacks(horizon.packCount)}`], ["Long run", "EV"]].map(([label, value], index) => <div key={label} className="relative"><i className={`mx-auto block h-4 w-4 rounded-full border-2 border-slate-950 ${index === 1 ? "bg-[var(--accent)] shadow-[0_0_0_5px_rgba(45,212,191,.16)]" : "bg-slate-500"}`} /><strong className="mt-3 block text-xs text-[var(--text-primary)]">{label}</strong><small className="mt-1 block text-[11px] text-[var(--text-secondary)]">{value}</small></div>)}</div></> : entitled ? <p className="mt-5 text-sm text-[var(--text-secondary)]">A confirmed EV Realization milestone is not available for this calculation run.</p> : <div data-ev-realization-lock className="mt-5"><p className="text-2xl font-semibold text-[var(--text-primary)]">Unlock the EV milestone</p><p className="mt-2 max-w-xl text-sm text-[var(--text-secondary)]">Index Plus shows the pack milestone where 80% of modeled openers reach at least 80% of long-run EV.</p><div aria-hidden="true" className="mt-5 h-1.5 rounded-full bg-[linear-gradient(90deg,rgba(100,116,139,.28),rgba(45,212,191,.22))]" /></div>}
  </section>;
}
