"use client";
import { useEffect, useMemo, useState } from "react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import ChartFrame from "./ChartFrame";
import { benchmarkMetric, benchmarkPosition, formatBenchmarkScore } from "./ripBenchmarkPresentation.mjs";
import { readBenchmarkHistory } from "@/lib/rankings/ripBenchmarkClient.mjs";
const WINDOWS = { "1D": 0, "7D": 6, "30D": 29, "3M": 89, "6M": 179, "1Y": 365 };
const COLORS = ["#2dd4bf", "#60a5fa", "#f59e0b", "#f472b6", "#a78bfa"];
const id = (target) => target?.target_id || target?.setId || target?.id;
const finite = (value) => value === null || value === undefined ? null : Number.isFinite(Number(value)) ? Number(value) : null;
const minusDays = (date, count) => new Date(new Date(`${date}T00:00:00Z`).getTime() - count * 86400000).toISOString().slice(0, 10);
const labelDate = (date) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(`${date}T00:00:00Z`));
function TooltipContent({ active, payload, names }) {
  const point = payload?.[0]?.payload; if (!active || !point) return null;
  return <div className="max-h-80 overflow-auto rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-page)] p-3 text-xs shadow-xl"><p className="font-semibold">{labelDate(point.date)}</p>{Object.entries(point.details || {}).map(([entityId, detail]) => <div key={entityId} className="mt-2 border-t border-[var(--border-subtle)] pt-2"><p className="font-semibold">{names[entityId]}</p><p>Modeled Return <strong>{(detail.return * 100).toFixed(1)}%</strong></p><p>Pokémon Average {detail.reference == null ? "Unavailable" : `${(detail.reference * 100).toFixed(1)}%`}</p><p>Difference {detail.reference == null ? "Unavailable" : `${((detail.return - detail.reference) * 100).toFixed(1)} pts`}</p><p>Financial RIP {formatBenchmarkScore(detail.score)}</p><p>{benchmarkPosition(detail.score)}</p>{detail.cost == null ? null : <p>Average Cost / Pack ${detail.cost.toFixed(2)}</p>}{detail.ev == null ? null : <p>Expected Value / Pack ${detail.ev.toFixed(2)}</p>}{detail.p50 == null ? null : <p>Typical Opening ${detail.p50.toFixed(2)}</p>}{detail.recover == null ? null : <p>Chance to Recover {(detail.recover * 100).toFixed(1)}%</p>}</div>)}</div>;
}
export default function FinancialReturnHistory({ targets = [], eras = [], benchmark = null }) {
  const [mode, setMode] = useState("sets"); const [windowKey, setWindowKey] = useState("30D"); const [history, setHistory] = useState(null); const [error, setError] = useState(null);
  const candidates = useMemo(() => mode === "sets" ? targets.map((target) => ({ entity_type: "set", entity_id: id(target), name: target.name, rank: benchmarkMetric(benchmark?.rows, "set", id(target), "financial").rank })).sort((a, b) => (a.rank ?? 999) - (b.rank ?? 999)) : eras.map((era) => ({ entity_type: "era", entity_id: era.eraId, name: era.eraName })), [mode, targets, eras, benchmark]);
  const [setSelection, setSetSelection] = useState([]); const [eraSelection, setEraSelection] = useState([]);
  useEffect(() => { if (!setSelection.length && mode === "sets") setSetSelection(candidates.slice(0, 3).map((item) => item.entity_id)); }, [mode, candidates, setSelection.length]);
  useEffect(() => { if (!eraSelection.length && mode === "eras") setEraSelection(candidates.map((item) => item.entity_id).slice(0, 5)); }, [mode, candidates, eraSelection.length]);
  const selectedIds = mode === "sets" ? setSelection : eraSelection; const selectionKey = selectedIds.join(","); const selected = useMemo(() => candidates.filter((item) => selectedIds.includes(item.entity_id)), [candidates, selectedIds]);
  const endDate = benchmark?.freshness?.benchmarkMarketDate || benchmark?.market_date; const startDate = windowKey === "ALL" ? (history?.historyAvailableFrom || minusDays(endDate, 365)) : minusDays(endDate, WINDOWS[windowKey]);
  useEffect(() => { if (!endDate || !selected.length) return; let live = true; setError(null); readBenchmarkHistory(selected, { startDate, endDate }).then((value) => { if (live) setHistory(value); }).catch((reason) => { if (live) setError(reason.message); }); return () => { live = false; }; }, [selected, windowKey, startDate, endDate]);
  const names = Object.fromEntries(candidates.map((item) => [item.entity_id, item.name]));
  const points = useMemo(() => { if (!history) return []; const byDate = new Map(); for (let cursor = new Date(`${startDate}T00:00:00Z`), end = new Date(`${endDate}T00:00:00Z`); cursor <= end; cursor = new Date(cursor.getTime() + 86400000)) { const date = cursor.toISOString().slice(0, 10); byDate.set(date, { date, details: {}, reference: finite(history.openingEconomicsReferences?.[date]?.modeled_return_on_spend) }); } for (const row of history.rows || []) { if (row.metric_key !== "financial" || !selectedIds.includes(row.entity_id)) continue; const point = byDate.get(row.market_date); if (!point) continue; const ret = finite(row.modeled_return_on_spend); if (ret === null) continue; point[`e_${row.entity_id}`] = ret * 100; point.details[row.entity_id] = { return: ret, reference: point.reference, score: row.benchmark_status === "available" ? finite(row.benchmark_score) : null, cost: finite(row.cost_per_pack), ev: finite(row.expected_value_per_pack), p50: finite(row.p50_value_per_pack), recover: finite(row.chance_to_recover_cost) }; } for (const point of byDate.values()) point.pokemon = point.reference === null ? null : point.reference * 100; return [...byDate.values()]; }, [history, startDate, endDate, selectionKey]);
  const toggle = (entityId) => { const setter = mode === "sets" ? setSetSelection : setEraSelection; setter((current) => current.includes(entityId) ? current.filter((value) => value !== entityId) : current.length < 5 ? [...current, entityId] : current); };
  return <div className="mt-5" data-financial-return-history><h3 className="text-base font-semibold">Financial Return vs Pokémon Average</h3><p className="mt-1 text-xs text-[var(--text-secondary)]">Published modeled return on spend; missing publication dates remain gaps.</p><div className="mt-3 flex flex-wrap gap-2"><div>{["sets", "eras"].map((value) => <button key={value} type="button" onClick={() => setMode(value)} aria-pressed={mode === value} className="mr-1 rounded-full border px-3 py-1 text-xs">{value === "sets" ? "Sets" : "Eras"}</button>)}</div><div>{[...Object.keys(WINDOWS), "ALL"].map((value) => <button key={value} type="button" onClick={() => setWindowKey(value)} aria-pressed={windowKey === value} className="mr-1 rounded px-2 py-1 text-xs">{value}</button>)}</div></div><div className="mt-2 flex max-h-24 flex-wrap gap-1 overflow-auto">{candidates.map((item) => <button type="button" key={item.entity_id} onClick={() => toggle(item.entity_id)} aria-pressed={selectedIds.includes(item.entity_id)} className="rounded-full border px-2 py-1 text-[10px]">{item.name}</button>)}</div>{error ? <p role="alert" className="mt-4 text-sm text-red-300">{error}</p> : <><ChartFrame className="mt-4 h-[20rem]"><ResponsiveContainer><LineChart data={points}><CartesianGrid strokeOpacity={0.2} strokeDasharray="2 8" /><XAxis dataKey="date" tickFormatter={labelDate} minTickGap={24} /><YAxis tickFormatter={(value) => `${value}%`} /><Tooltip content={<TooltipContent names={names} />} /><Legend /><Line dataKey="pokemon" name="Pokémon Average" stroke="#fff" strokeDasharray="5 5" dot={false} connectNulls={false} />{selected.map((item, index) => <Line key={item.entity_id} dataKey={`e_${item.entity_id}`} name={item.name} stroke={COLORS[index]} connectNulls={false} dot={{ r: 3 }} />)}</LineChart></ResponsiveContainer></ChartFrame><ol className="sr-only" aria-label="Visible modeled return history">{points.flatMap((point) => Object.entries(point.details).map(([entityId, detail]) => <li key={`${point.date}:${entityId}`}>{names[entityId]}, {labelDate(point.date)}: modeled return {(detail.return * 100).toFixed(1)} percent; Pokémon average {detail.reference == null ? "unavailable" : `${(detail.reference * 100).toFixed(1)} percent`}.</li>))}</ol></>}</div>;
}
