import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
const component = fs.readFileSync(new URL("./simulation-evidence/OpeningOutcomeProfileSection.jsx", import.meta.url), "utf8");
const report = fs.readFileSync(new URL("./SimulationFullReport.jsx", import.meta.url), "utf8");
const article = fs.readFileSync(new URL("../articles/EvResearchLiveExamples.jsx", import.meta.url), "utf8");
const css = fs.readFileSync(new URL("./RipDecisionPage.module.css", import.meta.url), "utf8");
test("one shared outcome profile implementation serves the set report and article", () => { assert.ok(report.includes('import OpeningOutcomeProfileSection from "./simulation-evidence/OpeningOutcomeProfileSection.jsx"')); assert.ok(article.includes('import OpeningOutcomeProfileSection from "@/components/explore/simulation-evidence/OpeningOutcomeProfileSection.jsx"')); assert.ok(component.includes("selectOpeningOutcomeProfileV1(openingOutcomeProfile, calculationRunId)")); });
test("first glance uses out-of-100 language and avoids profit claims", () => { assert.ok(component.includes("out of 100 modeled packs return less than half the pack price")); assert.ok(!component.toLowerCase().includes("profit")); });
test("primary bar keeps exact probability mass and labeled break-even boundary", () => { assert.ok(component.includes("flexGrow: r.probability")); assert.ok(component.includes("flexBasis: 0")); assert.ok(!component.includes("Math.max(r.probability")); assert.ok(component.includes("index === 1 ? <b>PACK COST</b>")); const barRule = css.match(/\.outcomeProfileBar\s*\{([^}]*)\}/)?.[1] || ""; assert.ok(!/\bgap\s*:/.test(barRule)); });
test("exact buckets remain under native progressive disclosure", () => { assert.ok(component.includes("View full outcome breakdown")); assert.ok(component.includes("outcome.details.map")); assert.match(css, /\.outcomeProfileRows,\.outcomeProfileCallouts\s*\{\s*grid-template-columns:\s*1fr/); });
