"use client";
import FinancialRipHistoryChart from "./FinancialRipHistoryChart";
import { money, ratioAsPercent } from "./openingEconomicsSelector.mjs";
const Dash = () => <span className="text-[var(--text-secondary)] opacity-60">—</span>;
export default function OpeningEconomicsDistribution({ scope, targets = [], openingSets = [], eras = [], marketDate = null }) {
  const metrics = [["Modeled Return on Spend", ratioAsPercent(scope.modeledReturnOnSpend)], ["Typical Retention", ratioAsPercent(scope.typicalRetention)], ["Chance to Recover Cost", ratioAsPercent(scope.chanceToRecoverCost)], ["Entertainment Cost / Pack", money(scope.averageEntertainmentCostPerPack)]];
  const values = [["Average Cost / Pack", money(scope.averageCostPerPack)], ["Expected Value / Pack", money(scope.averageModelBreakEvenPerPack)], ["Typical Opening / Pack", money(scope.typicalOpeningPerPack)]];
  return <section className="set-glass-surface overflow-hidden rounded-2xl border border-[var(--border-subtle)] bg-[var(--surface-page)]/35 p-4 sm:p-5" data-opening-economics-distribution><div className="grid grid-cols-2 gap-4 border-b border-[var(--border-subtle)] pb-4 lg:grid-cols-4">{metrics.map(([label, value]) => <div key={label}><p className="text-[10px] font-medium uppercase tracking-[0.08em] text-[var(--text-secondary)]">{label}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{value ?? <Dash />}</p></div>)}</div><div className="grid grid-cols-3 gap-3 border-b border-[var(--border-subtle)] py-4">{values.map(([label, value]) => <div key={label}><p className="text-[9px] font-medium uppercase tracking-[0.08em] text-[var(--text-secondary)]">{label}</p><p className="mt-1 text-lg font-semibold tabular-nums">{value ?? <Dash />}</p></div>)}</div><FinancialRipHistoryChart targets={targets} openingSets={openingSets} eras={eras} marketDate={marketDate} /></section>;
}
