"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import ExploreTableClient from "./ExploreTableClient";
import SegmentedControl from "@/components/ui/SegmentedControl";
import DarkSelect from "@/components/ui/DarkSelect";
import TableSearchInput from "@/components/ui/TableSearchInput";
import InfoPopover from "@/components/ui/InfoPopover";
import { RipScoreBadge, RipTierMark } from "./RipScoreBadge.jsx";
import { buildTcgSetHrefFromTarget } from "@/lib/explore/ripStatisticsRouting";
import { getTierTone } from "@/lib/explore/interpretationTone";
import { formatPublicRipScore } from "@/constants/exploreRankingConfig";
import styles from "./explore.module.css";

const FAMILY_SORT_OPTIONS = [{value:"overallRipScore",label:"Sort: Overall RIP"},{value:"financialRipScore",label:"Sort: Financial RIP"},{value:"collectorAppealScore",label:"Sort: Collector Appeal"},{value:"marketPrice",label:"Sort: Market Price"},{value:"expectedValue",label:"Sort: Expected Value"},{value:"chanceToRecoverCost",label:"Sort: Chance to Recover Cost"}];
const OVERALL_SORT_OPTIONS = [{value:"overallRipScore",label:"Sort: Overall RIP"},{value:"financialRipScore",label:"Sort: Financial RIP"},{value:"collectorAppealScore",label:"Sort: Collector Appeal"},{value:"unitPrice",label:"Sort: Unit Price"},{value:"expectedValue",label:"Sort: Expected Value"},{value:"chanceToRecoverCapital",label:"Sort: Chance to Recover Cost"}];
const money = new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2});
const wholeMoney = new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const HELP={overall:"Overall RIP combines Financial RIP and Collector Appeal to compare how favorable this product is to open.",tier:"Tier summarizes this product's Overall RIP score using the canonical S–F score bands.",financial:"How favorable this product's modeled financial outcome profile is relative to its current price.",collector:"How strong the set's collector-facing appeal is under the current Collector Appeal model.",market:"The current tracked market price used for this product's RIP calculations.",ev:"Average modeled value across simulated openings.",recovery:"The modeled probability that an opening returns at least the product's current market price.",format:"How this product ranks against other products in the same sealed-product format."};
const BUDGET_HELP="Ranks whole-product opening strategies that fit within the selected spending limit. inDex compares the maximum number of whole units of each eligible product that can be opened within that budget. Unused money is not included in the RIP score. Full Market uses the current dynamic budget required to include every eligible modeled product.";
const number=v=>Number.isFinite(Number(v))&&v!==null&&v!==""?Number(v):null;
const pluralFamilyLabel=label=>({"Elite Trainer Box":"Elite Trainer Boxes","Pokémon Center Elite Trainer Box":"Pokémon Center Elite Trainer Boxes","Booster Box":"Booster Boxes","Enhanced Booster Box":"Enhanced Booster Boxes"}[label]||`${label}s`);

export function filterAndSortProducts(products,query,sortKey){const needle=String(query||"").trim().toLocaleLowerCase();return(Array.isArray(products)?products:[]).filter(p=>!needle||[p?.productName,p?.setName].some(v=>String(v||"").toLocaleLowerCase().includes(needle))).slice().sort((a,b)=>{const av=number(a?.[sortKey]),bv=number(b?.[sortKey]);if(av===null)return bv===null?Number(a.budgetRank||a.familyRank)-Number(b.budgetRank||b.familyRank):1;if(bv===null)return-1;return bv-av||Number(a.budgetRank||a.familyRank)-Number(b.budgetRank||b.familyRank);});}
const score=v=>number(v)===null?"Unavailable":`${formatPublicRipScore(v)} / 10`;
const recovery=v=>{const n=number(v);return n===null?"Unavailable":`${(100*(n>1?n/100:n)).toFixed(1)}%`;};
function productHref(p){const base=buildTcgSetHrefFromTarget({target_type:"set",target_id:p.setId,name:p.setName});return`${base}?sealedProduct=${encodeURIComponent(p.sealedProductId)}`;}
export function productFormatStrength(p){const rank=number(p?.familyRank),size=number(p?.familySize),tier=String(p?.familyTier||"").toUpperCase();const heading=rank===1?"Format leader":tier==="S"?"Elite in format":tier==="A"?"Strong in format":tier==="B"?"Competitive in format":"Ranks within format";return{heading,detail:rank&&size?`#${rank} of ${size} ${pluralFamilyLabel(p?.productFamilyLabel||"product")}`:"Format rank unavailable"};}
function FormatStrength({product:p}){const text=productFormatStrength(p),tone=p?.familyTier?getTierTone(p.familyTier):null;return <div data-product-format-strength className="flex min-w-[10rem] items-start gap-2.5"><span aria-hidden="true" className="mt-1 h-2.5 w-2.5 flex-none rotate-45 border" style={{borderColor:tone?.accentColor||"var(--accent)"}}/><span><strong className="block text-xs text-[var(--text-primary)]">{text.heading}</strong><span className="mt-1 block text-[10.5px] text-[var(--text-secondary)]">{text.detail}</span></span></div>;}
function HeaderWithInfo({children,text}){return <span className="inline-flex items-center gap-1 whitespace-nowrap">{children}<InfoPopover text={text}/></span>;}
function Strategy({p}){return <span className="mt-1 block text-[10.5px] text-[var(--text-secondary)]">{p.quantity} {Number(p.quantity)===1?"unit":"units"} · {money.format(p.actualCommittedCapital)} committed</span>;}

function ProductRankingsTable({products,query,setQuery,sortKey,setSortKey,title,subtitle,overall=false,budgetOptions=[],selectedBudgetKey="",setSelectedBudgetKey}){
 const rank=p=>overall?p.budgetRank:p.familyRank,tier=p=>overall?p.budgetTier:p.familyTier,price=overall?"unitPrice":"marketPrice",recover=overall?"chanceToRecoverCapital":"chanceToRecoverCost";
 return <section className={`${styles.surface} set-glass-surface`} aria-label={`${title} rankings`}><div className={`${styles.divider} grid gap-3 px-4 py-3 md:grid-cols-[minmax(0,1fr)_16rem_minmax(0,1fr)] md:items-center`}><div><div className="flex items-center gap-1.5"><h2 className="font-semibold text-[var(--text-primary)]">{title}</h2>{overall?<InfoPopover text={BUDGET_HELP}/>:null}</div><p className="text-xs text-[var(--text-secondary)]">{subtitle}</p></div><TableSearchInput value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products or sets..." ariaLabel="Search products or sets" containerClassName="md:justify-self-center"/><div className="flex min-w-0 flex-col gap-2 sm:flex-row md:justify-self-end">{overall?<DarkSelect ariaLabel="Opening Budget" value={selectedBudgetKey} onChange={setSelectedBudgetKey} options={budgetOptions} className="w-full md:min-w-[12rem]"/>:null}<DarkSelect ariaLabel="Sort products" value={sortKey} onChange={setSortKey} options={overall?OVERALL_SORT_OPTIONS:FAMILY_SORT_OPTIONS} className="w-full md:min-w-[12rem]"/></div></div>
 {products.length?<><div className="hidden overflow-x-auto md:block"><table className={styles.table}><caption className="sr-only">{title}. Sorting preserves official {overall?"budget":"family"} rank.</caption><thead className={styles.head}><tr><th>Rank</th><th>Product / Set</th><th><HeaderWithInfo text={HELP.overall}>Overall RIP</HeaderWithInfo></th><th><HeaderWithInfo text={HELP.tier}>Tier</HeaderWithInfo></th><th><HeaderWithInfo text={HELP.financial}>Financial RIP</HeaderWithInfo></th><th><HeaderWithInfo text={HELP.collector}>Collector Appeal</HeaderWithInfo></th><th><HeaderWithInfo text={overall?"The current price of one natural product unit.":HELP.market}>{overall?"Unit Price":"Market Price"}</HeaderWithInfo></th><th><HeaderWithInfo text={overall?"Expected value of the complete persisted multi-unit opening strategy.":HELP.ev}>Expected Value</HeaderWithInfo></th><th><HeaderWithInfo text={overall?"Probability that the strategy recovers its actual committed capital, not the unused budget ceiling.":HELP.recovery}>Chance to Recover Cost</HeaderWithInfo></th><th><HeaderWithInfo text={HELP.format}>Format Strength</HeaderWithInfo></th></tr></thead><tbody>{products.map(p=><tr key={p.sealedProductId} className={styles.row}><td className={styles.numeric}>#{rank(p)}</td><td><Link href={productHref(p)} className={styles.rowLink}><span className="block font-semibold text-[var(--text-primary)]">{p.productName}</span><span className="text-xs text-[var(--text-secondary)]">{p.setName} · {p.productFamilyLabel}</span>{overall?<Strategy p={p}/>:null}</Link></td><td className={styles.numeric}><RipScoreBadge score={p.overallRipScore} tier={tier(p)}/></td><td className="text-center"><RipTierMark tier={tier(p)}/></td><td className={styles.numeric}>{score(p.financialRipScore)}</td><td className={styles.numeric}>{score(p.collectorAppealScore)}</td><td className={styles.numeric}>{number(p[price])===null?"Unavailable":money.format(p[price])}</td><td className={styles.numeric}>{number(p.expectedValue)===null?"Unavailable":money.format(p.expectedValue)}</td><td className={styles.numeric}>{recovery(p[recover])}</td><td><FormatStrength product={p}/></td></tr>)}</tbody></table></div><div className="space-y-2 p-3 md:hidden">{products.map(p=><Link key={p.sealedProductId} href={productHref(p)} className={`${styles.mobileRow} grid grid-cols-[2rem_minmax(0,1fr)_auto_auto] items-center gap-2.5`}><b className="text-right">#{rank(p)}</b><div className="min-w-0"><p className="truncate font-semibold">{p.productName}</p><p className="truncate text-xs text-[var(--text-secondary)]">{p.setName}</p>{overall?<Strategy p={p}/>:null}</div><RipScoreBadge score={p.overallRipScore} tier={tier(p)} compact/><RipTierMark tier={tier(p)}/></Link>)}</div></>:<p className="px-4 py-12 text-center text-sm text-[var(--text-secondary)]">{overall?"No eligible products match your search at this budget.":"No products match your search."}</p>}</section>;
}
function OverallProductRankings({overall,query,setQuery,sortKey,setSortKey,selectedBudgetKey,setSelectedBudgetKey}){const options=(overall?.availableBudgets||[]).map(e=>({value:e.key,label:e.budgetType==="full_market"?`Budget: Full Market (${wholeMoney.format(overall.fullMarketBudget)})`:`Budget: ${wholeMoney.format(e.targetBudget)}`}));const cohort=overall?.cohorts?.[selectedBudgetKey]||{rows:[],rankedCount:0};const products=useMemo(()=>filterAndSortProducts(cohort.rows,query,sortKey),[cohort.rows,query,sortKey]);if(!overall?.available)return <section className={`${styles.surface} set-glass-surface`}><p className="px-4 py-12 text-center text-sm text-[var(--text-secondary)]">Overall product rankings are temporarily unavailable.</p></section>;const context=cohort.budgetType==="full_market"?`Full Market (${wholeMoney.format(overall.fullMarketBudget)})`:`${wholeMoney.format(cohort.targetBudget)} opening budget`;return <ProductRankingsTable products={products} query={query} setQuery={setQuery} sortKey={sortKey} setSortKey={setSortKey} title="Best Products to Rip" subtitle={`Cross-format rankings at the selected opening budget · ${context} · ${cohort.rankedCount} ranked`} overall budgetOptions={options} selectedBudgetKey={selectedBudgetKey} setSelectedBudgetKey={setSelectedBudgetKey}/>;}

export default function ProductFamilyRankingsClient({targets,productFamilyRankings,overallProductRankings,loadError}){const families=productFamilyRankings?.families||{},entries=Object.entries(families).filter(([,b])=>Number(b?.count)>0);const[view,setView]=useState("sets"),[sortKey,setSortKey]=useState("overallRipScore"),[query,setQuery]=useState(""),[selectedBudgetKey,setSelectedBudgetKey]=useState(overallProductRankings?.defaultBudgetKey||"");const selected=families[view],products=useMemo(()=>filterAndSortProducts(selected?.products,query,sortKey),[selected,query,sortKey]),productsActive=view!=="sets";const selectView=next=>{setQuery("");setSortKey("overallRipScore");setView(next);},changeView=next=>selectView(next==="products"?"overall":"sets");return <><SegmentedControl className="mb-3 inline-block" ariaLabel="Ranking view" variant="primary" value={productsActive?"products":"sets"} onChange={changeView} options={[{value:"sets",label:"Sets"},{value:"products",label:"Products"}]}/>{productsActive?<nav aria-label="Product family" className="mb-3 flex gap-2 overflow-x-auto pb-1"><button type="button" onClick={()=>selectView("overall")} aria-pressed={view==="overall"} className={`${styles.productFamilyTab} ${view==="overall"?styles.productFamilyTabActive:""}`}>Overall</button>{entries.map(([family,b])=><button key={family} type="button" onClick={()=>selectView(family)} aria-pressed={view===family} className={`${styles.productFamilyTab} ${view===family?styles.productFamilyTabActive:""}`}>{pluralFamilyLabel(b.label)}</button>)}</nav>:null}{view==="sets"?<ExploreTableClient targets={targets} loadError={loadError}/>:view==="overall"?<OverallProductRankings overall={overallProductRankings} query={query} setQuery={setQuery} sortKey={sortKey} setSortKey={setSortKey} selectedBudgetKey={selectedBudgetKey} setSelectedBudgetKey={setSelectedBudgetKey}/>:<ProductRankingsTable products={products} query={query} setQuery={setQuery} sortKey={sortKey} setSortKey={setSortKey} title={`Best ${pluralFamilyLabel(selected?.label)} to Rip`} subtitle={`Compared only with ${pluralFamilyLabel(selected?.label)} · ${selected?.count} ranked`}/>}</>;}
