import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
const source=fs.readFileSync(path.resolve("components/explore/ProductFamilyRankingsClient.jsx"),"utf8");
const page=fs.readFileSync(path.resolve("app/Explore/page.js"),"utf8");
test("Products defaults to Overall through the dedicated reader",()=>{assert.match(source,/next === "products" \? "overall" : "sets"/);assert.ok(page.includes("initialOverallProductRankings={initialOverallProductRankings}"));assert.ok(source.includes("/api/explore/product-rankings/overall?budget="));assert.ok(!page.includes("payload?.overallProductRankings"));});
test("Overall retains dynamic budgets and loading",()=>{assert.ok(source.includes('useState("full_market")'));assert.ok(source.includes('selected?.type === "full_market"'));assert.ok(source.includes('result?.status === "loading"'));assert.ok(!source.includes("1350"));assert.equal((source.match(/ariaLabel="Opening Budget"/g)||[]).length,1);});
test("relative scores and public tier drive rendering",()=>{assert.ok(source.includes("overallRipRelativeScore"));assert.ok(source.includes("financialRipRelativeScore"));assert.match(source,/tier = \(p\) => p\.publicTier/);assert.ok(source.includes("collectorAppealScore"));});
test("search and sort preserve stored rank",()=>{assert.ok(source.includes("filterAndSortProducts"));assert.match(source,/a\.budgetRank \|\| a\.familyRank/);assert.ok(source.includes("#{rank(p)}"));});
test("desktop and mobile share one product table",()=>{assert.equal((source.match(/function ProductRankingsTable/g)||[]).length,1);assert.equal((source.match(/<table className=/g)||[]).length,1);assert.ok(source.includes("<Strategy p={p}"));assert.ok(source.includes("compact"));});
test("navigation declares the exact stable family progression",()=>{const expected=["loose_booster_pack","sleeved_booster_pack","booster_bundle","elite_trainer_box","half_booster_box","pokemon_center_elite_trainer_box","booster_box","enhanced_booster_box"];let cursor=-1;for(const family of expected){const next=source.indexOf(`"${family}"`,cursor+1);assert.ok(next>cursor,family);cursor=next;}assert.ok(source.includes("orderProductFamilyEntries(families)"));});
test("Overall has dedicated style and icon hooks",()=>{assert.ok(source.includes("data-overall-product-tab"));assert.ok(source.includes("productFamilyTabOverall"));assert.ok(source.includes("productFamilyTabOverallIcon"));});
test("unknown populated families append with a warning",()=>{assert.match(source,/unknown = populated\.filter/);assert.match(source,/return \[\.\.\.known, \.\.\.unknown\]/);assert.ok(source.includes("unplaced product families"));});
