import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import { canonicalMetricRows, readChaseAccessibilitySetRanking, readFinancialSetRanking, readSetCollectorAppealRanking } from "./setMetricRankingSelectors.mjs";

const table = fs.readFileSync(new URL("./SetMetricRankingsTable.jsx", import.meta.url), "utf8");
const registry = fs.readFileSync(new URL("./setRankingViews.mjs", import.meta.url), "utf8");
const overview = fs.readFileSync(new URL("./RankingsOverviewHighlights.jsx", import.meta.url), "utf8");
const lazy = fs.readFileSync(new URL("./RankingsLazyClient.jsx", import.meta.url), "utf8");

const target = { name: "Authority Set", era: "Era A", median_value: 4.2, modelBreakEvenPrice: 6.5, pack_cost: 10, prob_profit: 0.18, financialRipV4: { leaderNormalizedScore: 81, rank: 8, cohortSize: 22, tier: "A", status: "available" }, publicCollectorAppealContractV1: { collectorAppeal: { relativeScore: 77, rank: 6, rankedSetCount: 22, tier: "B" }, components: { rosterDesirability: { score: 84 }, desirableOutcomeFrequency: { rawValue: 0.19, displayPercent: 19 } } }, setRipV1: { chaseAccessibility: { publicScore: 72, percent: 4.25, setRank: 9, setCohortSize: 22, chaseDepth: 3, status: "available" } }, rankingsChase: { cardName: "Published Chase", currentMarketPrice: 100, impliedOddsOneInN: 321 } };

test("Financial uses V4 published score/rank and authoritative supporting economics", () => { const row = readFinancialSetRanking(target); assert.deepEqual([row.publicScore, row.rank, row.cohortSize, row.tier], [81, 8, 22, "A"]); assert.deepEqual([row.typicalOpening, row.modelBreakEven, row.modeledReturnPercent, row.chanceToBeatCost], [4.2, 6.5, 65, 0.18]); });
test("Collector agrees with canonical presentation and reads only two scored factors", () => { const row = readSetCollectorAppealRanking(target); assert.deepEqual([row.publicScore, row.rank, row.cohortSize, row.tier], [77, 6, 22, "B"]); assert.deepEqual([row.rosterScore, row.frequencyRawValue, row.frequencyDisplayPercent], [84, 0.19, 19]); for (const forbidden of ["Treatment", "Scarcity", "Artist"]) assert.ok(!table.includes(forbidden)); });
test("Chase uses Set authority, published rank, and published chase odds", () => { const row = readChaseAccessibilitySetRanking(target); assert.deepEqual([row.publicScore, row.rank, row.cohortSize, row.chaseDepth], [72, 9, 22, 3]); assert.deepEqual([row.chase.name, row.chase.oneInPacks], ["Published Chase", 321]); assert.ok(!table.includes("currentMarketPrice /")); });
test("Era filtering preserves global canonical rank", () => { const other = { ...target, name: "Other", era: "Era B", financialRipV4: { ...target.financialRipV4, rank: 1 } }; const rows = canonicalMetricRows([other, target], readFinancialSetRanking, "Era A"); assert.equal(rows.length, 1); assert.equal(readFinancialSetRanking(rows[0]).rank, 8); });
test("missing headline values stay unavailable rather than zero", () => { assert.equal(readFinancialSetRanking({ financialRipV4: { leaderNormalizedScore: null } }).publicScore, null); assert.equal(readSetCollectorAppealRanking({}).publicScore, null); assert.equal(readChaseAccessibilitySetRanking({ setRipV1: { chaseAccessibility: { publicScore: null } } }).publicScore, null); });
test("registry makes four views Plus while RIP and Pack Economics remain public/mixed", () => { assert.equal((registry.match(/requiredPlan: INDEX_PLAN_PLUS/g) || []).length, 4); assert.match(registry, /ripScore[^\n]+requiredPlan: null/); assert.match(registry, /packEconomics[^\n]+requiredPlan: null/); });
test("Overview remains public-only and no per-tab Set endpoint exists", () => { for (const paid of ["Financial RIP", "Collector Appeal", "Chase Accessibility", "familyScores"]) assert.ok(!overview.includes(paid)); assert.equal((lazy.match(/lens\?lens=sets/g) || []).length, 1); for (const endpoint of ["lens=financial", "lens=collector", "lens=chase"]) assert.ok(!lazy.includes(endpoint)); });
test("dedicated tables distinguish units and render a truthful empty-filter state", () => { assert.ok(table.includes("Roster Desirability (0–100)")); assert.ok(table.includes("No ranked sets match the current filters.")); });
