from .blackBolt import SetBlackBoltConfig
from .destinedRivals import SetDestinedRivalsConfig
from .journeyTogether import SetJourneyTogetherConfig
from .obsidianFlames import SetObsidianFlamesConfig
from .paldeaEvolved import SetPaldeaEvolvedConfig
from .paldeanFates import SetPaldeanFatesConfig
from .paradoxRift import SetParadoxRiftConfig
from .prismaticEvolutions import SetPrismaticEvolutionsConfig
from .scarletAndViolet151 import Set151Config
from .scarletAndVioletBase import SetScarletAndVioletBaseConfig
from .shroudedFable import SetShroudedFableConfig
from .stellarCrown import SetStellarCrownConfig
from .surgingSparks import SetSurgingSparksConfig
from .temporalForces import SetTemporalForcesConfig
from .twilightMasquerade import SetTwilightMasqueradeConfig
from .whiteFlare import SetWhiteFlareConfig


SET_CONFIG_MAP = {
    'blackBolt' : SetBlackBoltConfig,
    'destinedRivals' : SetDestinedRivalsConfig,
    'journeyTogether' : SetJourneyTogetherConfig,
    'obsidianFlames' : SetObsidianFlamesConfig,
    'paldeaEvolved' : SetPaldeaEvolvedConfig,
    'paldeanFates' : SetPaldeanFatesConfig,
    'paradoxRift' : SetParadoxRiftConfig,
    'prismaticEvolutions' : SetPrismaticEvolutionsConfig,
    'scarletAndViolet151' : Set151Config,
    'scarletAndVioletBase' : SetScarletAndVioletBaseConfig,
    'shroudedFable' : SetShroudedFableConfig,
    'stellarCrown' : SetStellarCrownConfig,
    'surgingSparks' : SetSurgingSparksConfig,
    'temporalForces' : SetTemporalForcesConfig,
    'twilightMasquerade' : SetTwilightMasqueradeConfig,
    'whiteFlare' : SetWhiteFlareConfig,
}

SET_ALIAS_MAP = {
    # Scarlet & Violet 151
    "151": "scarletAndViolet151",
    "sv151": "scarletAndViolet151",
    "scarlet and violet 151": "scarletAndViolet151",
    "scarlet & violet 151": "scarletAndViolet151",
    "sv 151": "scarletAndViolet151",
    "s&v151": "scarletAndViolet151",
    "sv-151": "scarletAndViolet151",
    "sv one five one": "scarletAndViolet151",
    "scarlet violet 151": "scarletAndViolet151",
    "scarlet 151": "scarletAndViolet151",
    "violet 151": "scarletAndViolet151",
    "s v 151": "scarletAndViolet151",
    "scarletandviolet151": "scarletAndViolet151",
    "scarletviolet151": "scarletAndViolet151",
    "s&v 151": "scarletAndViolet151",
    "sv151 set": "scarletAndViolet151",
    "151 set": "scarletAndViolet151",
    "151 sv": "scarletAndViolet151",
    "sv gen1": "scarletAndViolet151",
    "scarlet violet gen1": "scarletAndViolet151",
    "sv og": "scarletAndViolet151",
    "sv original": "scarletAndViolet151",

    # Black Bolt
    "blackbolt": "blackBolt",
    "black bolt": "blackBolt",
    "blackbolts": "blackBolt",
    "black bolts": "blackBolt",
    "bb": "blackBolt",
    "bbolt": "blackBolt",
    "blk bolt": "blackBolt",
    "blkbolt": "blackBolt",
    "blackblt": "blackBolt",
    "blak bolt": "blackBolt",
    "black bol": "blackBolt",
    "bolt black": "blackBolt",
    "bolt blk": "blackBolt",
    "black b": "blackBolt",
    "bb set": "blackBolt",
    "set black bolt": "blackBolt",
    "black bolt set": "blackBolt",
    "blackbol": "blackBolt",
    "blck bolt": "blackBolt",
    "bolts black": "blackBolt",
    "bolt set": "blackBolt",
    "black set": "blackBolt",
    "b b": "blackBolt",
    "blbolt": "blackBolt",
    "bk bolt": "blackBolt",

    # Destined Rivals
    "destined rivals": "destinedRivals",
    "destined rival": "destinedRivals",
    "destinedrivals": "destinedRivals",
    "destinedrival": "destinedRivals",
    "dr": "destinedRivals",
    "d rivals": "destinedRivals",
    "dest riv": "destinedRivals",
    "dest rival": "destinedRivals",
    "dest rivs": "destinedRivals",
    "d.r.": "destinedRivals",
    "rivals destined": "destinedRivals",
    "rival destined": "destinedRivals",
    "destind rivals": "destinedRivals",
    "destine rivals": "destinedRivals",
    "destin rivals": "destinedRivals",
    "destine rvals": "destinedRivals",
    "destiny rivals": "destinedRivals",
    "rivals set": "destinedRivals",
    "destined set": "destinedRivals",
    "set destined rivals": "destinedRivals",
    "dr set": "destinedRivals",
    "d rivals set": "destinedRivals",
    "dest riv set": "destinedRivals",
    "destnd rivals": "destinedRivals",

    # Journey Together
    "journey together": "journeyTogether",
    "journeytogther": "journeyTogether",
    "j together": "journeyTogether",
    "jt": "journeyTogether",
    "jrny together": "journeyTogether",
    "journy together": "journeyTogether",
    "journey 2gether": "journeyTogether",
    "2gether journey": "journeyTogether",
    "journey tgther": "journeyTogether",
    "journey togther": "journeyTogether",
    "journey togethr": "journeyTogether",
    "journey togher": "journeyTogether",
    "togther journey": "journeyTogether",
    "togethr journey": "journeyTogether",
    "together journey": "journeyTogether",
    "journey-together": "journeyTogether",
    "jrn together": "journeyTogether",
    "jny together": "journeyTogether",
    "jt set": "journeyTogether",
    "journey set": "journeyTogether",
    "together set": "journeyTogether",
    "journey2gether": "journeyTogether",
    "jrny2gthr": "journeyTogether",
    "j togethr": "journeyTogether",
    "jrny tgthr": "journeyTogether",

    # Obsidian Flames
    "obsidian flames": "obsidianFlames",
    "obsidian flame": "obsidianFlames",
    "obsidianflames": "obsidianFlames",
    "obsidianflame": "obsidianFlames",
    "obsid flames": "obsidianFlames",
    "obsid flame": "obsidianFlames",
    "obsidflames": "obsidianFlames",
    "obsidflame": "obsidianFlames",
    "obsi flames": "obsidianFlames",
    "obsi flame": "obsidianFlames",
    "obsi": "obsidianFlames",
    "flames obsidian": "obsidianFlames",
    "flame obsidian": "obsidianFlames",
    "ob": "obsidianFlames",
    "of": "obsidianFlames",
    "obsidain flames": "obsidianFlames",
    "obisdian flames": "obsidianFlames",
    "obsidien flames": "obsidianFlames",
    "obsidean flames": "obsidianFlames",
    "obisdian flame": "obsidianFlames",
    "obs flame": "obsidianFlames",
    "obs flames": "obsidianFlames",
    "obs flame set": "obsidianFlames",
    "obsidian set": "obsidianFlames",
    "flames set": "obsidianFlames",

    # Paldea Evolved
    "paldea evolved": "paldeaEvolved",
    "paldeaevolved": "paldeaEvolved",
    "paldea ev": "paldeaEvolved",
    "paldea evo": "paldeaEvolved",
    "pe": "paldeaEvolved",
    "pal evo": "paldeaEvolved",
    "p evo": "paldeaEvolved",
    "paldea-evolved": "paldeaEvolved",
    "paldea evlvd": "paldeaEvolved",
    "palde evolved": "paldeaEvolved",
    "palde ev": "paldeaEvolved",
    "p ev": "paldeaEvolved",
    "paldea set": "paldeaEvolved",
    "paldea evolved set": "paldeaEvolved",
    "set paldea evolved": "paldeaEvolved",
    "p.e.": "paldeaEvolved",
    "paldeaevo": "paldeaEvolved",
    "palevo": "paldeaEvolved",
    "paldevo": "paldeaEvolved",
    "p evo set": "paldeaEvolved",
    "paldea ev set": "paldeaEvolved",
    "evolved paldea": "paldeaEvolved",
    "pal deaevolved": "paldeaEvolved",
    "paldeaev": "paldeaEvolved",

    # Paldean Fates
    "paldean fates": "paldeanFates",
    "paldeanfates": "paldeanFates",
    "pal fate": "paldeanFates",
    "pf": "paldeanFates",
    "pal fates": "paldeanFates",
    "pal fate": "paldeanFates",
    "paldean fate": "paldeanFates",
    "fates paldean": "paldeanFates",
    "fate paldean": "paldeanFates",
    "palden fates": "paldeanFates",
    "paldean fats": "paldeanFates",
    "paldean faes": "paldeanFates",
    "p fate": "paldeanFates",
    "pfates": "paldeanFates",
    "pal fate set": "paldeanFates",
    "paldean set": "paldeanFates",
    "fates set": "paldeanFates",
    "pf set": "paldeanFates",
    "p.f.": "paldeanFates",
    "paldfates": "paldeanFates",
    "paldfate": "paldeanFates",
    "paldean f8s": "paldeanFates",
    "paldean ft": "paldeanFates",
    "p fate pal": "paldeanFates",

    # Paradox Rift
    "paradox rift": "paradoxRift",
    "paradoxrift": "paradoxRift",
    "pr": "paradoxRift",
    "p rift": "paradoxRift",
    "para rift": "paradoxRift",
    "parado rift": "paradoxRift",
    "paradox rif": "paradoxRift",
    "pdx rift": "paradoxRift",
    "paradox rf": "paradoxRift",
    "rift paradox": "paradoxRift",
    "rift para": "paradoxRift",
    "p rft": "paradoxRift",
    "prdox rift": "paradoxRift",
    "paradoxf": "paradoxRift",
    "para rft": "paradoxRift",
    "paradox set": "paradoxRift",
    "rift set": "paradoxRift",
    "pr set": "paradoxRift",
    "p.r.": "paradoxRift",
    "paradox rft": "paradoxRift",
    "pdxr": "paradoxRift",
    "pdxrift": "paradoxRift",
    "prdx rift": "paradoxRift",
    "pradox rift": "paradoxRift",
    "paradox rifft": "paradoxRift",

    # Prismatic Evolutions
    "prismatic evolution": "prismaticEvolutions",
    "prismaticevolution": "prismaticEvolutions",
    "pris evo": "prismaticEvolutions",
    "prism evo": "prismaticEvolutions",
    "prismatic evo": "prismaticEvolutions",
    "prismatic": "prismaticEvolutions",
    "pris": "prismaticEvolutions",
    "pevo": "prismaticEvolutions",
    "prsm evo": "prismaticEvolutions",
    "prsm evol": "prismaticEvolutions",
    "p evo prism": "prismaticEvolutions",
    "prismaticevo": "prismaticEvolutions",
    "prism evolution": "prismaticEvolutions",
    "evolution prismatic": "prismaticEvolutions",
    "evo prismatic": "prismaticEvolutions",
    "p evo": "prismaticEvolutions",
    "pris ev": "prismaticEvolutions",
    "p evo set": "prismaticEvolutions",
    "prism evo set": "prismaticEvolutions",
    "pris evo set": "prismaticEvolutions",
    "prism evol set": "prismaticEvolutions",
    "pris evolution": "prismaticEvolutions",
    "prsmc evo": "prismaticEvolutions",
    "prsm evo set": "prismaticEvolutions",

    # Scarlet & Violet Base
    "scarlet violet base": "scarletAndVioletBase",
    "scarlet & violet base": "scarletAndVioletBase",
    "sv base": "scarletAndVioletBase",
    "scarlet and violet base": "scarletAndVioletBase",
    "svb": "scarletAndVioletBase",
    "s v base": "scarletAndVioletBase",
    "sv-base": "scarletAndVioletBase",
    "sv base set": "scarletAndVioletBase",
    "base scarlet violet": "scarletAndVioletBase",
    "base sv": "scarletAndVioletBase",
    "svbase": "scarletAndVioletBase",
    "scarletvioletbase": "scarletAndVioletBase",
    "scarletandvioletbase": "scarletAndVioletBase",
    "s&v base": "scarletAndVioletBase",
    "svbse": "scarletAndVioletBase",
    "svb set": "scarletAndVioletBase",
    "base set sv": "scarletAndVioletBase",
    "base set scarlet violet": "scarletAndVioletBase",
    "base s&v": "scarletAndVioletBase",
    "scarlet base": "scarletAndVioletBase",
    "violet base": "scarletAndVioletBase",
    "sv b": "scarletAndVioletBase",
    "sv bse": "scarletAndVioletBase",

    # Shrouded Fable
    "shrouded fable": "shroudedFable",
    "shroudedfable": "shroudedFable",
    "sf": "shroudedFable",
    "shroud fable": "shroudedFable",
    "shrouded fabl": "shroudedFable",
    "shrouded fab": "shroudedFable",
    "fable shrouded": "shroudedFable",
    "fable shroud": "shroudedFable",
    "s fable": "shroudedFable",
    "shroud fabl": "shroudedFable",
    "shroudfable": "shroudedFable",
    "shr fable": "shroudedFable",
    "shr fbl": "shroudedFable",
    "shrouded set": "shroudedFable",
    "fable set": "shroudedFable",
    "sf set": "shroudedFable",
    "s.f.": "shroudedFable",
    "shr fbl set": "shroudedFable",
    "shroud fbl": "shroudedFable",
    "shroud fable set": "shroudedFable",
    "shrouded fabls": "shroudedFable",
    "shrouded fabl set": "shroudedFable",
    "shroud fab": "shroudedFable",

    # Stellar Crown
    "stellar crown": "stellarCrown",
    "stellarcrown": "stellarCrown",
    "sc": "stellarCrown",
    "stel crown": "stellarCrown",
    "stlr crown": "stellarCrown",
    "st crown": "stellarCrown",
    "stellar crn": "stellarCrown",
    "crown stellar": "stellarCrown",
    "crown stlr": "stellarCrown",
    "stell crown": "stellarCrown",
    "stelr crown": "stellarCrown",
    "stellar crwn": "stellarCrown",
    "stel crown set": "stellarCrown",
    "stellar set": "stellarCrown",
    "crown set": "stellarCrown",
    "sc set": "stellarCrown",
    "s.c.": "stellarCrown",
    "stlr set": "stellarCrown",
    "stell crn": "stellarCrown",
    "stell set": "stellarCrown",
    "st crown set": "stellarCrown",
    "crown st": "stellarCrown",
    "stelcrn": "stellarCrown",

    # Surging Sparks
    "surging sparks": "surgingSparks",
    "surge sparks": "surgingSparks",
    "surging spark": "surgingSparks",
    "surge spark": "surgingSparks",
    "surgingsparks": "surgingSparks",
    "surgesparks": "surgingSparks",
    "surg sparks": "surgingSparks",
    "surg spark": "surgingSparks",
    "ss": "surgingSparks",
    "ssparks": "surgingSparks",
    "s spark": "surgingSparks",
    "surging sp": "surgingSparks",
    "surge sp": "surgingSparks",
    "surgeing sparks": "surgingSparks",
    "surgeing spark": "surgingSparks",
    "surjing sparks": "surgingSparks",
    "suring sparks": "surgingSparks",
    "surging sparx": "surgingSparks",
    "surging sporks": "surgingSparks",
    "sparks surging": "surgingSparks",
    "spark surging": "surgingSparks",
    "sparx": "surgingSparks",
    "surging-sparks": "surgingSparks",
    "surge-sparks": "surgingSparks",
    "surge-n-sparks": "surgingSparks",

    # Temporal Forces
    "temporal forces": "temporalForces",
    "temporal force": "temporalForces",
    "temp forces": "temporalForces",
    "temp force": "temporalForces",
    "temporalforces": "temporalForces",
    "tempforces": "temporalForces",
    "t forces": "temporalForces",
    "t force": "temporalForces",
    "tf": "temporalForces",
    "tempf": "temporalForces",
    "tempo forces": "temporalForces",
    "tempo force": "temporalForces",
    "temprol forces": "temporalForces",
    "temprol force": "temporalForces",
    "temproal forces": "temporalForces",
    "temproal force": "temporalForces",
    "tempral forces": "temporalForces",
    "tempral force": "temporalForces",
    "tempural forces": "temporalForces",
    "time forces": "temporalForces",
    "time force": "temporalForces",
    "forces temporal": "temporalForces",
    "force temporal": "temporalForces",
    "temporal-f": "temporalForces",
    "t-forces": "temporalForces",

    # Twilight Masquerade
    "twilight masquerade": "twilightMasquerade",
    "twilight masque": "twilightMasquerade",
    "twilight mask": "twilightMasquerade",
    "twilightmasquerade": "twilightMasquerade",
    "twilightmasq": "twilightMasquerade",
    "t masque": "twilightMasquerade",
    "t mask": "twilightMasquerade",
    "tm": "twilightMasquerade",
    "twlight masquerade": "twilightMasquerade",
    "twilite masquerade": "twilightMasquerade",
    "twilite masque": "twilightMasquerade",
    "twilite mask": "twilightMasquerade",
    "twiligt masquerade": "twilightMasquerade",
    "twighlight masquerade": "twilightMasquerade",
    "twighlite masquerade": "twilightMasquerade",
    "twighlite mask": "twilightMasquerade",
    "twilite masq": "twilightMasquerade",
    "maskerade twilight": "twilightMasquerade",
    "masquerade twilight": "twilightMasquerade",
    "maskerade": "twilightMasquerade",
    "masq": "twilightMasquerade",
    "twilight-msq": "twilightMasquerade",
    "twilight-msqr": "twilightMasquerade",
    "tw-masq": "twilightMasquerade",
    "t-masq": "twilightMasquerade",

    # White Flare
    "white flare": "whiteFlare",
    "whiteflar": "whiteFlare",
    "whiteflair": "whiteFlare",
    "whiteflare": "whiteFlare",
    "white flr": "whiteFlare",
    "w flare": "whiteFlare",
    "wf": "whiteFlare",
    "wfl": "whiteFlare",
    "w f": "whiteFlare",
    "whte flare": "whiteFlare",
    "whit flare": "whiteFlare",
    "whight flare": "whiteFlare",
    "whyt flare": "whiteFlare",
    "whteflar": "whiteFlare",
    "whitflar": "whiteFlare",
    "wh flare": "whiteFlare",
    "whte flar": "whiteFlare",
    "flair white": "whiteFlare",
    "flare white": "whiteFlare",
    "white-flare": "whiteFlare",
    "w-flare": "whiteFlare",
    "wht flare": "whiteFlare",
    "wt flare": "whiteFlare",
    "wh flare": "whiteFlare",
    "whitefl": "whiteFlare",
    "wflare": "whiteFlare",
}
