"""Parts 1-5: the one-pack distribution layer.

Everything in this module is TIER A: it reads the exact, persisted
million-pack outcome vector produced by the authoritative simulation and does
arithmetic on it. Nothing here re-simulates, re-prices, or re-derives a metric
that already has a canonical owner elsewhere in the repository.

TWO REUSE DECISIONS WORTH READING BEFORE EDITING
------------------------------------------------
1. **Tail selection is RANK-based, not threshold-based.** ``rank_tail_count`` is
   literally Financial RIP V3's ``TailBuckets`` rule, imported by constant and
   proven equal by contract test. It matters: Pokemon pack outcomes are dense
   with ties (the largest single-value plateau in the live cohort holds ~1% of
   all mass), so ``values >= np.percentile(values, 99)`` can select materially
   more than 1% of observations while still calling itself "the top 1%". Rank
   buckets fix the MASS, so "top 1% EV share" means exactly that.

2. **Top-1% share and top-1% conditional mean already exist.** They are Financial
   RIP V3's ``jackpotValueShare`` and ``jackpotTailMeanValue``. This module
   computes the same quantities under the same rule and extends the rule to 5%
   and 10%; it does not invent a second definition of the top 1%.

PERCENTILE CONVENTION
---------------------
``numpy.percentile`` with linear interpolation, matching
``derived_metrics._safe_percentile`` and ``run_simulation_v2``. The persisted
``simulation_run_summary.median_value`` is produced that way, so P50 here is the
same P50 the product publishes - not a near-miss.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Dict, Mapping, Optional, Sequence, Tuple

import numpy as np

from backend.calculations.evr.financial_rip_v3_config import (
    FINANCIAL_RIP_V3_TAIL_CONTRACT_VERSION,
)

from .version import (
    OUTCOME_TAIL_QUANTILES,
    RETURN_RATIO_BUCKETS,
)

PERCENTILE_METHOD = "numpy_linear_interpolation"


# ---------------------------------------------------------------------------
# Rank-exact tail selection (the canonical rule, generalized)
# ---------------------------------------------------------------------------

def rank_tail_count(n: int, quantile: float) -> int:
    """Observations in the top ``quantile`` tail, by RANK.

    This is ``TailBuckets``' rule verbatim::

        top_1_count = max(1, math.ceil(n * JACKPOT_TAIL_SHARE))

    generalized to an arbitrary tail share. ``test_ev_representativeness_distribution``
    asserts it reproduces ``TailBuckets.top_1_count`` and ``top_5_count`` exactly,
    so the two can never drift apart silently.
    """
    if n <= 0:
        raise ValueError("rank_tail_count requires a non-empty sample")
    if not 0.0 < quantile <= 1.0:
        raise ValueError(f"tail quantile must be in (0, 1]; got {quantile}")
    return max(1, math.ceil(n * quantile))


@dataclass(frozen=True)
class OutcomeTail:
    """One rank-exact upper tail of a sorted outcome vector."""

    quantile: float
    observation_count: int
    realized_mass: float
    ev_share: Optional[float]
    conditional_mean: float
    entry_threshold: float

    def as_payload(self) -> Dict[str, Any]:
        return {
            "quantile": self.quantile,
            "observationCount": self.observation_count,
            "realizedMass": self.realized_mass,
            "evShare": self.ev_share,
            "conditionalTailMean": self.conditional_mean,
            "entryThresholdValue": self.entry_threshold,
        }


def compute_outcome_tails(
    sorted_values: np.ndarray,
    *,
    quantiles: Sequence[float] = OUTCOME_TAIL_QUANTILES,
) -> Dict[float, OutcomeTail]:
    """Parts 4.1-4.4: EV share and conditional mean of each upper tail.

    ``ev_share`` is ``sum(tail) / sum(all)`` - the share of the set's total
    simulated economic value generated by its best openings. That is a different
    question from P99 (a threshold) and from the conditional tail mean (an
    average), which is why all three are returned rather than one standing in
    for the others.

    ``ev_share`` is ``None`` when the total is non-positive: a share of nothing
    is not zero, it is undefined, and returning 0.0 would read as "the tail
    contributes nothing".
    """
    n = int(sorted_values.size)
    total = float(sorted_values.sum(dtype=np.float64))
    tails: Dict[float, OutcomeTail] = {}
    for quantile in quantiles:
        count = rank_tail_count(n, float(quantile))
        bucket = sorted_values[n - count:]
        bucket_sum = float(bucket.sum(dtype=np.float64))
        tails[float(quantile)] = OutcomeTail(
            quantile=float(quantile),
            observation_count=count,
            realized_mass=count / n,
            ev_share=(bucket_sum / total) if total > 0.0 else None,
            conditional_mean=float(bucket.mean()),
            entry_threshold=float(bucket[0]),
        )
    return tails


# ---------------------------------------------------------------------------
# Parts 1-3: baseline statistics, EV vs Typical, skewness diagnostics
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class BaselineDistribution:
    """Parts 1-3 for one outcome vector at one cost basis."""

    sample_size: int
    ev: float
    variance: float
    std_dev: float
    coefficient_of_variation: Optional[float]
    percentiles: Mapping[int, float]
    pack_cost: Optional[float]

    # Part 2
    ev_typical_gap_absolute: float
    ev_typical_gap_cost_normalized: Optional[float]
    typical_capture: Optional[float]
    relative_gap: Optional[float]

    # Part 3
    mean_abs_dev_about_median: float
    pearson_skew_2: Optional[float]
    groeneveld_meeden_skew: Optional[float]

    # Part 4
    tails: Mapping[float, OutcomeTail] = field(default_factory=dict)

    @property
    def p50(self) -> float:
        return float(self.percentiles[50])

    def as_payload(self) -> Dict[str, Any]:
        return {
            "sampleSize": self.sample_size,
            "ev": self.ev,
            "variance": self.variance,
            "stdDev": self.std_dev,
            "coefficientOfVariation": self.coefficient_of_variation,
            "percentiles": {str(k): v for k, v in sorted(self.percentiles.items())},
            "packCost": self.pack_cost,
            "evTypicalGapAbsolute": self.ev_typical_gap_absolute,
            "evTypicalGapCostNormalized": self.ev_typical_gap_cost_normalized,
            "typicalCapture": self.typical_capture,
            "relativeGap": self.relative_gap,
            "meanAbsDevAboutMedian": self.mean_abs_dev_about_median,
            "pearsonSkew2": self.pearson_skew_2,
            "groeneveldMeedenSkew": self.groeneveld_meeden_skew,
            "outcomeTails": {str(q): t.as_payload() for q, t in sorted(self.tails.items())},
            "percentileMethod": PERCENTILE_METHOD,
            "tailSelectionMethod": FINANCIAL_RIP_V3_TAIL_CONTRACT_VERSION,
        }


_PERCENTILE_GRID: Tuple[int, ...] = (5, 10, 25, 50, 75, 90, 95, 99)


def _safe_div(numerator: float, denominator: float, *, floor: float) -> Optional[float]:
    """Division that returns None instead of inf/NaN on a vanishing denominator.

    ``floor`` is an ABSOLUTE magnitude below which the ratio stops being
    meaningful rather than merely large. Part 2.3 asks explicitly for
    zero/near-zero EV to be handled; returning None says "not meaningful here",
    which a report can render as a dash. Returning a huge float would say
    "measured, and enormous".
    """
    if not math.isfinite(denominator) or abs(denominator) <= floor:
        return None
    result = numerator / denominator
    return result if math.isfinite(result) else None


def compute_baseline_distribution(
    values: np.ndarray,
    *,
    pack_cost: Optional[float] = None,
    sorted_values: Optional[np.ndarray] = None,
    tail_quantiles: Sequence[float] = OUTCOME_TAIL_QUANTILES,
    ev_floor: float = 1e-9,
) -> BaselineDistribution:
    """Parts 1-4 in one pass over the outcome vector.

    ``sorted_values`` may be supplied when the caller already sorted (sorting a
    million-element vector is the single most expensive operation here and the
    counterfactual layer sorts many variants of the same vector).
    """
    array = np.asarray(values, dtype=np.float64)
    n = int(array.size)
    if n == 0:
        raise ValueError("compute_baseline_distribution requires a non-empty outcome vector")

    ordered = np.sort(array) if sorted_values is None else np.asarray(sorted_values, dtype=np.float64)

    ev = float(array.mean())
    variance = float(array.var())
    std_dev = float(math.sqrt(variance))
    percentiles = {q: float(np.percentile(ordered, q)) for q in _PERCENTILE_GRID}
    p50 = percentiles[50]

    gap_absolute = ev - p50
    gap_cost = (
        _safe_div(gap_absolute, float(pack_cost), floor=ev_floor)
        if pack_cost is not None
        else None
    )
    typical_capture = _safe_div(p50, ev, floor=ev_floor)
    relative_gap = None if typical_capture is None else 1.0 - typical_capture

    # Groeneveld-Meeden's denominator: E[|X - median|], from the empirical
    # distribution as the brief requires. Computed on the sorted copy so the
    # allocation is reused rather than doubled.
    mean_abs_dev = float(np.abs(ordered - p50).mean())

    pearson_2 = _safe_div(3.0 * gap_absolute, std_dev, floor=ev_floor)
    gm_skew = _safe_div(gap_absolute, mean_abs_dev, floor=ev_floor)

    return BaselineDistribution(
        sample_size=n,
        ev=ev,
        variance=variance,
        std_dev=std_dev,
        coefficient_of_variation=_safe_div(std_dev, ev, floor=ev_floor),
        percentiles=percentiles,
        pack_cost=None if pack_cost is None else float(pack_cost),
        ev_typical_gap_absolute=gap_absolute,
        ev_typical_gap_cost_normalized=gap_cost,
        typical_capture=typical_capture,
        relative_gap=relative_gap,
        mean_abs_dev_about_median=mean_abs_dev,
        pearson_skew_2=pearson_2,
        groeneveld_meeden_skew=gm_skew,
        tails=compute_outcome_tails(ordered, quantiles=tail_quantiles),
    )


# ---------------------------------------------------------------------------
# Part 5: cost-normalized outcome distribution buckets
# ---------------------------------------------------------------------------

def compute_return_ratio_buckets(
    values: np.ndarray,
    cost: float,
    *,
    buckets: Sequence[Tuple[float, Optional[float]]] = RETURN_RATIO_BUCKETS,
) -> Dict[str, Any]:
    """Part 5: what fraction of openings landed in each economic band.

    Bucket membership is ``[floor, ceiling)`` with a final open-ended bucket,
    matching the existing ``compute_simulation_value_threshold_bins`` convention
    so two bucket contracts in the same repository do not disagree about edges.
    Coverage is asserted, not assumed: every outcome lands in exactly one bucket
    or the function raises.

    The ratio is ``outcome / cost``, so this answers "what fraction of what they
    paid did they get back" and is comparable across a $5.45 pack and a $28.92
    pack - which a dollar-denominated bucket cannot be.
    """
    array = np.asarray(values, dtype=np.float64)
    n = int(array.size)
    if n == 0:
        raise ValueError("compute_return_ratio_buckets requires a non-empty outcome vector")
    cost_f = float(cost)
    if not math.isfinite(cost_f) or cost_f <= 0.0:
        raise ValueError(f"return-ratio buckets require a positive finite cost; got {cost}")

    ratios = array / cost_f
    rows = []
    covered = 0
    cumulative = 0.0
    for order, (floor, ceiling) in enumerate(buckets, start=1):
        floor_f = float(floor)
        if ceiling is None:
            mask_count = int(np.count_nonzero(ratios >= floor_f))
            label = f">={_fmt_edge(floor_f)}x"
        else:
            ceiling_f = float(ceiling)
            mask_count = int(np.count_nonzero((ratios >= floor_f) & (ratios < ceiling_f)))
            label = f"{_fmt_edge(floor_f)}-{_fmt_edge(ceiling_f)}x"
        probability = mask_count / n
        cumulative += probability
        covered += mask_count
        rows.append(
            {
                "bucketOrder": order,
                "ratioFloor": floor_f,
                "ratioCeiling": None if ceiling is None else float(ceiling),
                "bucketLabel": label,
                "occurrenceCount": mask_count,
                "probability": probability,
                "cumulativeProbability": cumulative,
            }
        )

    if covered != n:
        raise ValueError(
            f"return-ratio bucket coverage mismatch: counted={covered}, total={n}. "
            "The bucket edges do not partition the outcome range."
        )

    return {
        "cost": cost_f,
        "sampleSize": n,
        "buckets": rows,
        "ratioPercentiles": {
            str(q): float(np.percentile(ratios, q)) for q in _PERCENTILE_GRID
        },
        "meanReturnRatio": float(ratios.mean()),
        "bucketContractVersion": "ev_representativeness_return_ratio_v1",
    }


def _fmt_edge(value: float) -> str:
    return str(int(value)) if float(value).is_integer() else f"{value:g}"
