-- Canonical steady-state contract for Price Storage V2 shadow infrastructure.
-- This migration is intentionally idempotent so it can safely reconcile an
-- environment where the remote-history bridge migrations were already applied.
-- It does NOT switch production readers and does NOT delete legacy history.

BEGIN;

CREATE TABLE IF NOT EXISTS public.card_variant_price_events_v2 (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_variant_id uuid NOT NULL REFERENCES public.card_variants(id) ON DELETE CASCADE,
    condition_id uuid NOT NULL REFERENCES public.conditions(id),
    source text NOT NULL,
    currency text NOT NULL,
    effective_date date NOT NULL,
    event_type text NOT NULL CHECK (event_type IN ('PRICE','UNPRICED','RETURNED_TO_MARKET','RETIRED')),
    market_price numeric,
    high_price numeric,
    low_price numeric,
    source_observation_id uuid,
    source_created_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT card_variant_price_events_v2_day_unique
        UNIQUE (card_variant_id, condition_id, source, currency, effective_date),
    CONSTRAINT card_variant_price_events_v2_price_state_check CHECK (
        (event_type IN ('PRICE','RETURNED_TO_MARKET') AND market_price IS NOT NULL)
        OR (event_type IN ('UNPRICED','RETIRED') AND market_price IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS public.card_variant_price_current_v2 (
    card_variant_id uuid NOT NULL REFERENCES public.card_variants(id) ON DELETE CASCADE,
    condition_id uuid NOT NULL REFERENCES public.conditions(id),
    source text NOT NULL,
    currency text NOT NULL,
    event_id bigint NOT NULL REFERENCES public.card_variant_price_events_v2(id) ON DELETE CASCADE,
    effective_date date NOT NULL,
    state text NOT NULL CHECK (state IN ('PRICE','UNPRICED','RETURNED_TO_MARKET','RETIRED')),
    market_price numeric,
    high_price numeric,
    low_price numeric,
    source_observation_id uuid,
    updated_at timestamptz NOT NULL DEFAULT now(),
    last_observed_date date,
    last_observation_id uuid,
    last_observation_created_at timestamptz,
    PRIMARY KEY (card_variant_id, condition_id, source, currency)
);

CREATE INDEX IF NOT EXISTS card_variant_price_current_v2_event_id_idx
    ON public.card_variant_price_current_v2(event_id);

CREATE TABLE IF NOT EXISTS public.price_storage_v2_migration_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase text NOT NULL,
    captured_at timestamptz NOT NULL DEFAULT now(),
    database_size_bytes bigint,
    raw_observation_rows bigint,
    raw_observation_bytes bigint,
    interval_rows bigint,
    interval_bytes bigint,
    daily_state_rows bigint,
    daily_state_bytes bigint,
    monthly_rollup_rows bigint,
    monthly_rollup_bytes bigint,
    details jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.price_storage_v2_shadow_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id uuid NOT NULL REFERENCES public.sets(id) ON DELETE CASCADE,
    market_date date NOT NULL,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','processing','complete','failed')),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    last_error text,
    enqueued_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    completed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    source_completed_at timestamptz,
    CONSTRAINT price_storage_v2_shadow_queue_set_date_unique UNIQUE (set_id, market_date)
);

CREATE INDEX IF NOT EXISTS price_storage_v2_shadow_queue_pending_idx
    ON public.price_storage_v2_shadow_queue(status, market_date, id)
    WHERE status IN ('pending','failed');

CREATE TABLE IF NOT EXISTS public.pokemon_market_price_intervals_v2_shadow (
    card_variant_id uuid NOT NULL,
    set_id uuid NOT NULL,
    valid_from date NOT NULL,
    valid_to date,
    market_price numeric NOT NULL CHECK (market_price > 0),
    PRIMARY KEY (card_variant_id, valid_from),
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE INDEX IF NOT EXISTS pokemon_market_price_intervals_v2_set_from_idx
    ON public.pokemon_market_price_intervals_v2_shadow(set_id, valid_from, card_variant_id)
    INCLUDE (valid_to, market_price);

CREATE INDEX IF NOT EXISTS pokemon_market_price_intervals_v2_open_idx
    ON public.pokemon_market_price_intervals_v2_shadow(set_id, card_variant_id)
    INCLUDE (market_price, valid_from)
    WHERE valid_to IS NULL;

ALTER TABLE public.card_variant_price_events_v2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.card_variant_price_current_v2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_storage_v2_migration_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_storage_v2_shadow_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pokemon_market_price_intervals_v2_shadow ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.card_variant_price_events_v2 FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.card_variant_price_current_v2 FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.price_storage_v2_migration_audit FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.price_storage_v2_shadow_queue FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.pokemon_market_price_intervals_v2_shadow FROM PUBLIC, anon, authenticated;

GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.card_variant_price_events_v2 TO service_role;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.card_variant_price_current_v2 TO service_role;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.price_storage_v2_migration_audit TO service_role;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.price_storage_v2_shadow_queue TO service_role;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.pokemon_market_price_intervals_v2_shadow TO service_role;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE OR REPLACE FUNCTION public.rebuild_card_variant_price_events_v2_from_raw_scope(
    p_card_variant_ids uuid[]
)
RETURNS jsonb
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE
    v_event_rows bigint := 0;
    v_current_rows bigint := 0;
BEGIN
    IF p_card_variant_ids IS NULL OR cardinality(p_card_variant_ids) = 0 THEN
        RETURN jsonb_build_object('event_rows',0,'current_rows',0,'scope_variants',0);
    END IF;

    DELETE FROM public.card_variant_price_current_v2
    WHERE card_variant_id = ANY(p_card_variant_ids);

    DELETE FROM public.card_variant_price_events_v2
    WHERE card_variant_id = ANY(p_card_variant_ids);

    WITH normalized AS MATERIALIZED (
        SELECT
            observation.id AS source_observation_id,
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN') AS source,
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD') AS currency,
            observation.captured_at AS effective_date,
            observation.market_price,
            observation.high_price,
            observation.low_price,
            observation.created_at AS source_created_at,
            lag(observation.market_price) OVER price_order AS previous_market_price,
            lag(observation.high_price) OVER price_order AS previous_high_price,
            lag(observation.low_price) OVER price_order AS previous_low_price,
            row_number() OVER price_order AS sequence_number
        FROM public.card_variant_price_observations observation
        WHERE observation.card_variant_id = ANY(p_card_variant_ids)
          AND observation.captured_at IS NOT NULL
        WINDOW price_order AS (
            PARTITION BY observation.card_variant_id, observation.condition_id,
                COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN'),
                COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD')
            ORDER BY observation.captured_at, observation.created_at, observation.id
        )
    ), change_events AS (
        SELECT *
        FROM normalized
        WHERE market_price IS NOT NULL
          AND (
              sequence_number = 1
              OR market_price IS DISTINCT FROM previous_market_price
              OR high_price IS DISTINCT FROM previous_high_price
              OR low_price IS DISTINCT FROM previous_low_price
          )
    )
    INSERT INTO public.card_variant_price_events_v2(
        card_variant_id,condition_id,source,currency,effective_date,event_type,
        market_price,high_price,low_price,source_observation_id,source_created_at
    )
    SELECT card_variant_id,condition_id,source,currency,effective_date,'PRICE',
           market_price,high_price,low_price,source_observation_id,source_created_at
    FROM change_events
    ORDER BY card_variant_id,condition_id,source,currency,effective_date;

    GET DIAGNOSTICS v_event_rows = ROW_COUNT;

    WITH latest_event AS MATERIALIZED (
        SELECT * FROM (
            SELECT event_row.*,
                   row_number() OVER (
                       PARTITION BY event_row.card_variant_id,event_row.condition_id,event_row.source,event_row.currency
                       ORDER BY event_row.effective_date DESC,event_row.id DESC
                   ) AS latest_rank
            FROM public.card_variant_price_events_v2 event_row
            WHERE event_row.card_variant_id = ANY(p_card_variant_ids)
        ) ranked
        WHERE latest_rank = 1
    ), latest_observation AS MATERIALIZED (
        SELECT * FROM (
            SELECT
                observation.card_variant_id,
                observation.condition_id,
                COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN') AS source,
                COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD') AS currency,
                observation.id AS last_observation_id,
                observation.captured_at AS last_observed_date,
                observation.created_at AS last_observation_created_at,
                row_number() OVER (
                    PARTITION BY observation.card_variant_id,observation.condition_id,
                        COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN'),
                        COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD')
                    ORDER BY observation.captured_at DESC,observation.created_at DESC,observation.id DESC
                ) AS latest_rank
            FROM public.card_variant_price_observations observation
            WHERE observation.card_variant_id = ANY(p_card_variant_ids)
              AND observation.captured_at IS NOT NULL
              AND observation.market_price IS NOT NULL
        ) ranked
        WHERE latest_rank = 1
    )
    INSERT INTO public.card_variant_price_current_v2(
        card_variant_id,condition_id,source,currency,event_id,effective_date,state,
        market_price,high_price,low_price,source_observation_id,
        last_observed_date,last_observation_id,last_observation_created_at,updated_at
    )
    SELECT e.card_variant_id,e.condition_id,e.source,e.currency,e.id,e.effective_date,e.event_type,
           e.market_price,e.high_price,e.low_price,e.source_observation_id,
           o.last_observed_date,o.last_observation_id,o.last_observation_created_at,now()
    FROM latest_event e
    JOIN latest_observation o
      ON o.card_variant_id=e.card_variant_id
     AND o.condition_id=e.condition_id
     AND o.source=e.source
     AND o.currency=e.currency;

    GET DIAGNOSTICS v_current_rows = ROW_COUNT;
    RETURN jsonb_build_object(
        'event_rows',v_event_rows,
        'current_rows',v_current_rows,
        'scope_variants',cardinality(p_card_variant_ids)
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_price_storage_v2_set_date(
    p_set_id uuid,
    p_market_date date
)
RETURNS jsonb
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE
    v_day_rows bigint := 0;
    v_deleted_events bigint := 0;
    v_upserted_events bigint := 0;
    v_upserted_current bigint := 0;
BEGIN
    IF p_set_id IS NULL OR p_market_date IS NULL THEN
        RAISE EXCEPTION 'set_id and market_date are required';
    END IF;

    WITH day_rows AS MATERIALIZED (
        SELECT DISTINCT ON (
            observation.card_variant_id,observation.condition_id,
            COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN'),
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD')
        )
            observation.id AS source_observation_id,
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN') AS source,
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD') AS currency,
            observation.captured_at AS effective_date,
            observation.market_price,observation.high_price,observation.low_price,
            observation.created_at AS source_created_at
        FROM public.card_variant_price_observations observation
        JOIN public.card_variants variant ON variant.id=observation.card_variant_id
        JOIN public.cards card ON card.id=variant.card_id
        WHERE card.set_id=p_set_id
          AND observation.captured_at=p_market_date
          AND observation.market_price IS NOT NULL
        ORDER BY observation.card_variant_id,observation.condition_id,
                 COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN'),
                 COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD'),
                 observation.created_at DESC,observation.id DESC
    ), compared AS MATERIALIZED (
        SELECT d.*,prior.id AS prior_event_id,
               prior.market_price AS prior_market_price,
               prior.high_price AS prior_high_price,
               prior.low_price AS prior_low_price
        FROM day_rows d
        LEFT JOIN LATERAL (
            SELECT e.id,e.market_price,e.high_price,e.low_price
            FROM public.card_variant_price_events_v2 e
            WHERE e.card_variant_id=d.card_variant_id
              AND e.condition_id=d.condition_id
              AND e.source=d.source
              AND e.currency=d.currency
              AND e.effective_date<p_market_date
            ORDER BY e.effective_date DESC,e.id DESC
            LIMIT 1
        ) prior ON true
    )
    DELETE FROM public.card_variant_price_events_v2 e
    USING compared c
    WHERE e.card_variant_id=c.card_variant_id
      AND e.condition_id=c.condition_id
      AND e.source=c.source
      AND e.currency=c.currency
      AND e.effective_date=p_market_date
      AND c.prior_event_id IS NOT NULL
      AND c.market_price IS NOT DISTINCT FROM c.prior_market_price
      AND c.high_price IS NOT DISTINCT FROM c.prior_high_price
      AND c.low_price IS NOT DISTINCT FROM c.prior_low_price;
    GET DIAGNOSTICS v_deleted_events = ROW_COUNT;

    WITH day_rows AS MATERIALIZED (
        SELECT DISTINCT ON (
            observation.card_variant_id,observation.condition_id,
            COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN'),
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD')
        ) observation.*,
          COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN') AS normalized_source,
          COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD') AS normalized_currency
        FROM public.card_variant_price_observations observation
        JOIN public.card_variants variant ON variant.id=observation.card_variant_id
        JOIN public.cards card ON card.id=variant.card_id
        WHERE card.set_id=p_set_id
          AND observation.captured_at=p_market_date
          AND observation.market_price IS NOT NULL
        ORDER BY observation.card_variant_id,observation.condition_id,
                 COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN'),
                 COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD'),
                 observation.created_at DESC,observation.id DESC
    ), compared AS MATERIALIZED (
        SELECT d.*,
               prior.id AS prior_event_id,
               prior.market_price AS prior_market_price,
               prior.high_price AS prior_high_price,
               prior.low_price AS prior_low_price
        FROM day_rows d
        LEFT JOIN LATERAL (
            SELECT e.id,e.market_price,e.high_price,e.low_price
            FROM public.card_variant_price_events_v2 e
            WHERE e.card_variant_id=d.card_variant_id
              AND e.condition_id=d.condition_id
              AND e.source=d.normalized_source
              AND e.currency=d.normalized_currency
              AND e.effective_date<p_market_date
            ORDER BY e.effective_date DESC,e.id DESC
            LIMIT 1
        ) prior ON true
    )
    INSERT INTO public.card_variant_price_events_v2(
        card_variant_id,condition_id,source,currency,effective_date,event_type,
        market_price,high_price,low_price,source_observation_id,source_created_at
    )
    SELECT c.card_variant_id,c.condition_id,c.normalized_source,c.normalized_currency,c.captured_at,'PRICE',
           c.market_price,c.high_price,c.low_price,c.id,c.created_at
    FROM compared c
    WHERE c.prior_event_id IS NULL
       OR c.market_price IS DISTINCT FROM c.prior_market_price
       OR c.high_price IS DISTINCT FROM c.prior_high_price
       OR c.low_price IS DISTINCT FROM c.prior_low_price
    ON CONFLICT (card_variant_id,condition_id,source,currency,effective_date)
    DO UPDATE SET event_type=EXCLUDED.event_type,
                  market_price=EXCLUDED.market_price,
                  high_price=EXCLUDED.high_price,
                  low_price=EXCLUDED.low_price,
                  source_observation_id=EXCLUDED.source_observation_id,
                  source_created_at=EXCLUDED.source_created_at;
    GET DIAGNOSTICS v_upserted_events = ROW_COUNT;

    WITH day_rows AS MATERIALIZED (
        SELECT DISTINCT ON (
            observation.card_variant_id,observation.condition_id,
            COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN'),
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD')
        )
            observation.id AS last_observation_id,
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN') AS source,
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD') AS currency,
            observation.captured_at AS last_observed_date,
            observation.created_at AS last_observation_created_at
        FROM public.card_variant_price_observations observation
        JOIN public.card_variants variant ON variant.id=observation.card_variant_id
        JOIN public.cards card ON card.id=variant.card_id
        WHERE card.set_id=p_set_id
          AND observation.captured_at=p_market_date
          AND observation.market_price IS NOT NULL
        ORDER BY observation.card_variant_id,observation.condition_id,
                 COALESCE(NULLIF(trim(observation.source),''),'UNKNOWN'),
                 COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))),''),'USD'),
                 observation.created_at DESC,observation.id DESC
    ), resolved AS MATERIALIZED (
        SELECT d.*,e.id AS event_id,e.effective_date,e.event_type,e.market_price,e.high_price,e.low_price,e.source_observation_id
        FROM day_rows d
        JOIN LATERAL (
            SELECT e.*
            FROM public.card_variant_price_events_v2 e
            WHERE e.card_variant_id=d.card_variant_id
              AND e.condition_id=d.condition_id
              AND e.source=d.source
              AND e.currency=d.currency
              AND e.effective_date<=p_market_date
            ORDER BY e.effective_date DESC,e.id DESC
            LIMIT 1
        ) e ON true
    )
    INSERT INTO public.card_variant_price_current_v2(
        card_variant_id,condition_id,source,currency,event_id,effective_date,state,
        market_price,high_price,low_price,source_observation_id,
        last_observed_date,last_observation_id,last_observation_created_at,updated_at
    )
    SELECT card_variant_id,condition_id,source,currency,event_id,effective_date,event_type,
           market_price,high_price,low_price,source_observation_id,
           last_observed_date,last_observation_id,last_observation_created_at,now()
    FROM resolved
    ON CONFLICT (card_variant_id,condition_id,source,currency)
    DO UPDATE SET event_id=EXCLUDED.event_id,
                  effective_date=EXCLUDED.effective_date,
                  state=EXCLUDED.state,
                  market_price=EXCLUDED.market_price,
                  high_price=EXCLUDED.high_price,
                  low_price=EXCLUDED.low_price,
                  source_observation_id=EXCLUDED.source_observation_id,
                  last_observed_date=EXCLUDED.last_observed_date,
                  last_observation_id=EXCLUDED.last_observation_id,
                  last_observation_created_at=EXCLUDED.last_observation_created_at,
                  updated_at=now()
    WHERE public.card_variant_price_current_v2.last_observed_date IS NULL
       OR EXCLUDED.last_observed_date>=public.card_variant_price_current_v2.last_observed_date;
    GET DIAGNOSTICS v_upserted_current = ROW_COUNT;

    SELECT count(*) INTO v_day_rows
    FROM public.card_variant_price_observations observation
    JOIN public.card_variants variant ON variant.id=observation.card_variant_id
    JOIN public.cards card ON card.id=variant.card_id
    WHERE card.set_id=p_set_id
      AND observation.captured_at=p_market_date
      AND observation.market_price IS NOT NULL;

    RETURN jsonb_build_object(
        'set_id',p_set_id,'market_date',p_market_date,'day_rows',v_day_rows,
        'deleted_redundant_events',v_deleted_events,
        'upserted_events',v_upserted_events,
        'upserted_current_rows',v_upserted_current
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_pokemon_market_price_intervals_v2_shadow_set_from_date(
    p_set_id uuid,
    p_start_date date
)
RETURNS jsonb
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE
    v_deleted bigint := 0;
    v_reopened bigint := 0;
    v_inserted bigint := 0;
    v_closed_baselines bigint := 0;
BEGIN
    IF p_set_id IS NULL OR p_start_date IS NULL THEN
        RAISE EXCEPTION 'set_id and start_date are required';
    END IF;

    DELETE FROM public.pokemon_market_price_intervals_v2_shadow
    WHERE set_id=p_set_id AND valid_from>=p_start_date;
    GET DIAGNOSTICS v_deleted = ROW_COUNT;

    UPDATE public.pokemon_market_price_intervals_v2_shadow
    SET valid_to=NULL
    WHERE set_id=p_set_id
      AND valid_from<p_start_date
      AND valid_to IS NOT NULL
      AND valid_to>=p_start_date;
    GET DIAGNOSTICS v_reopened = ROW_COUNT;

    WITH scoped_metadata AS MATERIALIZED (
        SELECT card_variant_id,set_id
        FROM public.pokemon_market_explorer_card_current_metadata
        WHERE set_id=p_set_id
    ), ordered AS MATERIALIZED (
        SELECT e.card_variant_id,m.set_id,e.effective_date,e.market_price,
               lag(e.market_price) OVER (PARTITION BY e.card_variant_id ORDER BY e.effective_date,e.id) AS previous_market_price,
               row_number() OVER (PARTITION BY e.card_variant_id ORDER BY e.effective_date,e.id) AS sequence_number
        FROM public.card_variant_price_events_v2 e
        JOIN scoped_metadata m ON m.card_variant_id=e.card_variant_id
        WHERE e.condition_id='4f8d1181-670e-4aea-937c-4d98d2e531a6'::uuid
          AND e.source='TCGPlayer' AND e.currency='USD' AND e.market_price>0
    ), changes AS MATERIALIZED (
        SELECT card_variant_id,set_id,effective_date,market_price
        FROM ordered
        WHERE effective_date>=p_start_date
          AND (sequence_number=1 OR market_price IS DISTINCT FROM previous_market_price)
    ), intervals AS (
        SELECT card_variant_id,set_id,effective_date AS valid_from,
               lead(effective_date) OVER (PARTITION BY card_variant_id ORDER BY effective_date) AS valid_to,
               market_price
        FROM changes
    )
    INSERT INTO public.pokemon_market_price_intervals_v2_shadow(card_variant_id,set_id,valid_from,valid_to,market_price)
    SELECT card_variant_id,set_id,valid_from,valid_to,market_price FROM intervals;
    GET DIAGNOSTICS v_inserted = ROW_COUNT;

    WITH first_new AS (
        SELECT card_variant_id,min(valid_from) AS first_valid_from
        FROM public.pokemon_market_price_intervals_v2_shadow
        WHERE set_id=p_set_id AND valid_from>=p_start_date
        GROUP BY card_variant_id
    )
    UPDATE public.pokemon_market_price_intervals_v2_shadow baseline
    SET valid_to=first_new.first_valid_from
    FROM first_new
    WHERE baseline.card_variant_id=first_new.card_variant_id
      AND baseline.set_id=p_set_id
      AND baseline.valid_from<p_start_date
      AND baseline.valid_to IS NULL;
    GET DIAGNOSTICS v_closed_baselines = ROW_COUNT;

    RETURN jsonb_build_object(
        'set_id',p_set_id,'start_date',p_start_date,
        'deleted_tail_rows',v_deleted,'reopened_baselines',v_reopened,
        'inserted_tail_rows',v_inserted,'closed_baselines',v_closed_baselines
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.enqueue_price_storage_v2_completed_scrape_jobs(
    p_market_date date,
    p_limit integer DEFAULT 500
)
RETURNS jsonb
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE v_enqueued integer := 0;
BEGIN
    IF p_market_date IS NULL THEN RAISE EXCEPTION 'p_market_date is required'; END IF;
    IF p_limit IS NULL OR p_limit<1 OR p_limit>1000 THEN
        RAISE EXCEPTION 'p_limit must be between 1 and 1000';
    END IF;

    WITH completed AS MATERIALIZED (
        SELECT job.set_id,job.market_date,max(job.completed_at) AS source_completed_at
        FROM public.scrape_jobs job
        WHERE job.market_date=p_market_date
          AND job.status='completed'
          AND job.set_id IS NOT NULL
          AND job.completed_at IS NOT NULL
        GROUP BY job.set_id,job.market_date
        ORDER BY max(job.completed_at),job.set_id
        LIMIT p_limit
    ), upserted AS (
        INSERT INTO public.price_storage_v2_shadow_queue(
            set_id,market_date,status,attempts,last_error,enqueued_at,started_at,completed_at,updated_at,source_completed_at
        )
        SELECT set_id,market_date,'pending',0,NULL,now(),NULL,NULL,now(),source_completed_at
        FROM completed
        ON CONFLICT (set_id,market_date)
        DO UPDATE SET status='pending',last_error=NULL,started_at=NULL,completed_at=NULL,
                      updated_at=now(),source_completed_at=EXCLUDED.source_completed_at
        WHERE public.price_storage_v2_shadow_queue.source_completed_at IS NULL
           OR EXCLUDED.source_completed_at>public.price_storage_v2_shadow_queue.source_completed_at
           OR public.price_storage_v2_shadow_queue.status='failed'
        RETURNING 1
    )
    SELECT count(*) INTO v_enqueued FROM upserted;

    RETURN jsonb_build_object('market_date',p_market_date,'enqueued',v_enqueued);
END;
$$;

CREATE OR REPLACE FUNCTION public.process_price_storage_v2_shadow_queue(
    p_limit integer DEFAULT 20
)
RETURNS jsonb
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE
    v_job record;
    v_processed integer := 0;
    v_completed integer := 0;
    v_failed integer := 0;
    v_price_result jsonb;
    v_interval_result jsonb;
BEGIN
    IF p_limit IS NULL OR p_limit<1 OR p_limit>20 THEN
        RAISE EXCEPTION 'p_limit must be between 1 and 20';
    END IF;

    FOR v_job IN
        SELECT q.id,q.set_id,q.market_date
        FROM public.price_storage_v2_shadow_queue q
        WHERE q.status IN ('pending','failed') AND q.attempts<5
        ORDER BY q.market_date,q.id
        FOR UPDATE SKIP LOCKED
        LIMIT p_limit
    LOOP
        v_processed:=v_processed+1;
        UPDATE public.price_storage_v2_shadow_queue
        SET status='processing',attempts=attempts+1,started_at=now(),completed_at=NULL,last_error=NULL,updated_at=now()
        WHERE id=v_job.id;
        BEGIN
            v_price_result:=public.sync_price_storage_v2_set_date(v_job.set_id,v_job.market_date);
            v_interval_result:=public.sync_pokemon_market_price_intervals_v2_shadow_set_from_date(v_job.set_id,v_job.market_date);
            UPDATE public.price_storage_v2_shadow_queue
            SET status='complete',completed_at=now(),last_error=NULL,updated_at=now()
            WHERE id=v_job.id;
            v_completed:=v_completed+1;
        EXCEPTION WHEN OTHERS THEN
            UPDATE public.price_storage_v2_shadow_queue
            SET status='failed',completed_at=now(),last_error=left(SQLERRM,2000),updated_at=now()
            WHERE id=v_job.id;
            v_failed:=v_failed+1;
        END;
    END LOOP;

    RETURN jsonb_build_object('processed',v_processed,'completed',v_completed,'failed',v_failed);
END;
$$;

CREATE OR REPLACE FUNCTION public.run_price_storage_v2_shadow_cycle()
RETURNS jsonb
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE
    v_market_date date:=timezone('America/Phoenix',now())::date;
    v_previous jsonb;
    v_current jsonb;
    v_processed jsonb;
BEGIN
    v_previous:=public.enqueue_price_storage_v2_completed_scrape_jobs(v_market_date-1,1000);
    v_current:=public.enqueue_price_storage_v2_completed_scrape_jobs(v_market_date,1000);
    v_processed:=public.process_price_storage_v2_shadow_queue(20);
    RETURN jsonb_build_object(
        'phoenix_market_date',v_market_date,
        'previous_date_enqueue',v_previous,
        'current_date_enqueue',v_current,
        'queue_processing',v_processed
    );
END;
$$;

CREATE OR REPLACE VIEW public.card_market_usd_latest_by_condition_v2_shadow
WITH (security_invoker=true)
AS
SELECT
    c.id AS card_id,c.set_id,s.name AS set_name,c.name AS card_name,c.card_number,c.rarity,
    cv.id AS variant_id,cv.printing_type,cv.special_type,cv.edition,
    cur.condition_id,cond.name AS condition,cur.market_price,cur.high_price,cur.low_price,
    cur.currency,cur.source,cur.last_observed_date AS captured_at,
    cur.last_observation_created_at AS created_at
FROM public.card_variants cv
JOIN public.cards c ON c.id=cv.card_id
LEFT JOIN public.sets s ON s.id=c.set_id
JOIN public.card_variant_price_current_v2 cur ON cur.card_variant_id=cv.id AND cur.currency='USD'
LEFT JOIN public.conditions cond ON cond.id=cur.condition_id;

CREATE OR REPLACE VIEW public.simulation_input_cards_with_near_mint_price_v2_shadow
WITH (security_invoker=true)
AS
SELECT sic.*,
       cur.market_price AS current_near_mint_price,
       cur.last_observed_date AS current_near_mint_price_captured_at,
       cur.source AS current_near_mint_price_source
FROM public.simulation_input_cards sic
LEFT JOIN public.card_variant_price_current_v2 cur
  ON cur.card_variant_id=sic.card_variant_id
 AND cur.condition_id=sic.condition_id
 AND cur.currency='USD'
 AND cur.market_price>0;

CREATE OR REPLACE FUNCTION public.get_pokemon_market_explorer_compact_state_v2_shadow(
    p_set_ids uuid[],p_market_date date
)
RETURNS TABLE(
    market_date date,card_variant_id uuid,canonical_card_id uuid,set_id uuid,
    market_price numeric,price_effective_date date,card_name text,card_number text,
    rarity text,edition text,printing_type text,special_type text,image_url text,identity_basis text
)
LANGUAGE sql
STABLE
SET search_path TO ''
AS $$
    SELECT p_market_date,i.card_variant_id,m.canonical_card_id,i.set_id,i.market_price,i.valid_from,
           m.card_name,m.card_number,m.rarity,m.edition,m.printing_type,m.special_type,m.image_url,m.identity_basis
    FROM public.pokemon_market_price_intervals_v2_shadow i
    JOIN public.pokemon_market_explorer_card_current_metadata m ON m.card_variant_id=i.card_variant_id
    WHERE p_set_ids IS NOT NULL
      AND cardinality(p_set_ids)>0
      AND i.set_id=ANY(p_set_ids)
      AND i.valid_from<=p_market_date
      AND (i.valid_to IS NULL OR p_market_date<i.valid_to);
$$;

REVOKE ALL ON FUNCTION public.rebuild_card_variant_price_events_v2_from_raw_scope(uuid[]) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.sync_price_storage_v2_set_date(uuid,date) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.sync_pokemon_market_price_intervals_v2_shadow_set_from_date(uuid,date) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.enqueue_price_storage_v2_completed_scrape_jobs(date,integer) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.process_price_storage_v2_shadow_queue(integer) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.run_price_storage_v2_shadow_cycle() FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.get_pokemon_market_explorer_compact_state_v2_shadow(uuid[],date) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON TABLE public.card_market_usd_latest_by_condition_v2_shadow FROM PUBLIC,anon,authenticated;
REVOKE ALL ON TABLE public.simulation_input_cards_with_near_mint_price_v2_shadow FROM PUBLIC,anon,authenticated;

GRANT EXECUTE ON FUNCTION public.rebuild_card_variant_price_events_v2_from_raw_scope(uuid[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_price_storage_v2_set_date(uuid,date) TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_pokemon_market_price_intervals_v2_shadow_set_from_date(uuid,date) TO service_role;
GRANT EXECUTE ON FUNCTION public.enqueue_price_storage_v2_completed_scrape_jobs(date,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.process_price_storage_v2_shadow_queue(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.run_price_storage_v2_shadow_cycle() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_pokemon_market_explorer_compact_state_v2_shadow(uuid[],date) TO service_role;
GRANT SELECT ON TABLE public.card_market_usd_latest_by_condition_v2_shadow TO service_role;
GRANT SELECT ON TABLE public.simulation_input_cards_with_near_mint_price_v2_shadow TO service_role;

DO $$
DECLARE v_jobid bigint;
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname='pg_cron') THEN
        SELECT jobid INTO v_jobid FROM cron.job WHERE jobname='price-storage-v2-shadow-cycle' LIMIT 1;
        IF v_jobid IS NOT NULL THEN PERFORM cron.unschedule(v_jobid); END IF;
        PERFORM cron.schedule(
            'price-storage-v2-shadow-cycle',
            '*/15 * * * *',
            'select public.run_price_storage_v2_shadow_cycle();'
        );
    END IF;
END;
$$;

COMMENT ON TABLE public.card_variant_price_events_v2 IS
'Backend-only compact card price change-event history. Shadow authority while legacy readers remain active.';
COMMENT ON TABLE public.card_variant_price_current_v2 IS
'Backend-only current price state derived from Price Storage V2 events, including last-observed provenance.';
COMMENT ON TABLE public.pokemon_market_price_intervals_v2_shadow IS
'Backend-only compact Market Explorer interval candidate derived from V2 market-price transitions. Not a production authority.';
COMMENT ON TABLE public.price_storage_v2_shadow_queue IS
'Backend-only post-scrape queue. V2 failures must never fail legacy scrape/publication.';

COMMIT;
