CREATE TABLE IF NOT EXISTS public.card_variant_price_observation_ranges_v2 (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_variant_id uuid NOT NULL REFERENCES public.card_variants(id) ON DELETE CASCADE,
    condition_id uuid NOT NULL REFERENCES public.conditions(id),
    source text NOT NULL,
    currency text NOT NULL,
    observed_from date NOT NULL,
    observed_through date NOT NULL,
    observed_day_count integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT card_variant_price_observation_ranges_v2_valid_dates CHECK (observed_through >= observed_from),
    CONSTRAINT card_variant_price_observation_ranges_v2_positive_days CHECK (observed_day_count >= 1),
    CONSTRAINT card_variant_price_observation_ranges_v2_unique UNIQUE(card_variant_id,condition_id,source,currency,observed_from)
);

CREATE INDEX IF NOT EXISTS idx_cvpor_v2_variant_condition_range
ON public.card_variant_price_observation_ranges_v2(card_variant_id,condition_id,source,currency,observed_from,observed_through);

ALTER TABLE public.card_variant_price_observation_ranges_v2 ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.card_variant_price_observation_ranges_v2 FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.card_variant_price_observation_ranges_v2 TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.card_variant_price_observation_ranges_v2_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.rebuild_card_variant_price_observation_ranges_v2_from_raw_scope(p_card_variant_ids uuid[])
RETURNS jsonb
LANGUAGE plpgsql
SET search_path TO ''
AS $function$
DECLARE
    v_ranges bigint := 0;
BEGIN
    IF p_card_variant_ids IS NULL OR cardinality(p_card_variant_ids)=0 THEN
        RETURN jsonb_build_object('scopeVariants',0,'rangeRows',0);
    END IF;

    DELETE FROM public.card_variant_price_observation_ranges_v2 r
    WHERE r.card_variant_id=ANY(p_card_variant_ids);

    WITH observed_days AS MATERIALIZED (
        SELECT DISTINCT
            o.card_variant_id,
            o.condition_id,
            coalesce(nullif(trim(o.source),''),'UNKNOWN') AS source,
            coalesce(nullif(trim(both '"' from upper(trim(o.currency))),''),'USD') AS currency,
            o.captured_at AS observed_date
        FROM public.card_variant_price_observations o
        WHERE o.card_variant_id=ANY(p_card_variant_ids)
          AND o.captured_at IS NOT NULL
          AND o.market_price IS NOT NULL
          AND o.market_price>0
    ), flagged AS (
        SELECT d.*,
               CASE WHEN lag(d.observed_date) OVER w = d.observed_date - 1 THEN 0 ELSE 1 END AS new_range
        FROM observed_days d
        WINDOW w AS (
            PARTITION BY d.card_variant_id,d.condition_id,d.source,d.currency
            ORDER BY d.observed_date
        )
    ), grouped AS (
        SELECT f.*,
               sum(f.new_range) OVER (
                   PARTITION BY f.card_variant_id,f.condition_id,f.source,f.currency
                   ORDER BY f.observed_date
               ) AS range_group
        FROM flagged f
    )
    INSERT INTO public.card_variant_price_observation_ranges_v2(
        card_variant_id,condition_id,source,currency,
        observed_from,observed_through,observed_day_count
    )
    SELECT card_variant_id,condition_id,source,currency,
           min(observed_date),max(observed_date),count(*)::integer
    FROM grouped
    GROUP BY card_variant_id,condition_id,source,currency,range_group
    ORDER BY card_variant_id,condition_id,source,currency,min(observed_date);

    GET DIAGNOSTICS v_ranges=ROW_COUNT;
    RETURN jsonb_build_object('scopeVariants',cardinality(p_card_variant_ids),'rangeRows',v_ranges);
END;
$function$;

REVOKE ALL ON FUNCTION public.rebuild_card_variant_price_observation_ranges_v2_from_raw_scope(uuid[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rebuild_card_variant_price_observation_ranges_v2_from_raw_scope(uuid[]) TO service_role;

COMMENT ON TABLE public.card_variant_price_observation_ranges_v2 IS
'Backend-only lossless compression of positive-price raw observation presence by consecutive date ranges. Combined with Price Storage V2 price events, preserves whether a series had an observation on a date without storing one relational row per day.';