BEGIN;

CREATE TABLE IF NOT EXISTS public.price_storage_v2_shadow_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id uuid NOT NULL REFERENCES public.sets(id) ON DELETE CASCADE,
    market_date date NOT NULL,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','complete','failed')),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    last_error text,
    enqueued_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    completed_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT price_storage_v2_shadow_queue_set_date_unique UNIQUE (set_id, market_date)
);

CREATE INDEX IF NOT EXISTS price_storage_v2_shadow_queue_pending_idx
    ON public.price_storage_v2_shadow_queue (status, market_date, id)
    WHERE status IN ('pending','failed');

ALTER TABLE public.price_storage_v2_shadow_queue ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.price_storage_v2_shadow_queue FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.price_storage_v2_shadow_queue TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE OR REPLACE FUNCTION public.enqueue_price_storage_v2_shadow_set_date(
    p_set_id uuid,
    p_market_date date
)
RETURNS bigint
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE
    v_id bigint;
BEGIN
    IF p_set_id IS NULL OR p_market_date IS NULL THEN
        RAISE EXCEPTION 'set_id and market_date are required';
    END IF;

    INSERT INTO public.price_storage_v2_shadow_queue (
        set_id, market_date, status, attempts, last_error,
        enqueued_at, started_at, completed_at, updated_at
    )
    VALUES (
        p_set_id, p_market_date, 'pending', 0, NULL,
        now(), NULL, NULL, now()
    )
    ON CONFLICT (set_id, market_date)
    DO UPDATE SET
        status = 'pending',
        last_error = NULL,
        started_at = NULL,
        completed_at = NULL,
        updated_at = now()
    RETURNING id INTO v_id;

    RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_price_storage_v2_set_date(
    p_set_id uuid,
    p_market_date date
)
RETURNS jsonb
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE
    v_day_rows bigint := 0;
    v_deleted_events bigint := 0;
    v_upserted_events bigint := 0;
    v_upserted_current bigint := 0;
BEGIN
    IF p_set_id IS NULL OR p_market_date IS NULL THEN
        RAISE EXCEPTION 'set_id and market_date are required';
    END IF;

    SELECT count(*) INTO v_day_rows
    FROM (
        SELECT DISTINCT ON (
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN'),
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD')
        ) observation.id
        FROM public.card_variant_price_observations observation
        JOIN public.card_variants variant ON variant.id = observation.card_variant_id
        JOIN public.cards card ON card.id = variant.card_id
        WHERE card.set_id = p_set_id
          AND observation.captured_at = p_market_date
          AND observation.market_price IS NOT NULL
        ORDER BY
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN'),
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD'),
            observation.created_at DESC,
            observation.id DESC
    ) day_count;

    WITH day_rows AS MATERIALIZED (
        SELECT DISTINCT ON (
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN'),
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD')
        )
            observation.id AS source_observation_id,
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN') AS source,
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD') AS currency,
            observation.captured_at AS effective_date,
            observation.market_price,
            observation.high_price,
            observation.low_price,
            observation.created_at AS source_created_at
        FROM public.card_variant_price_observations observation
        JOIN public.card_variants variant ON variant.id = observation.card_variant_id
        JOIN public.cards card ON card.id = variant.card_id
        WHERE card.set_id = p_set_id
          AND observation.captured_at = p_market_date
          AND observation.market_price IS NOT NULL
        ORDER BY
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN'),
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD'),
            observation.created_at DESC,
            observation.id DESC
    ), compared AS MATERIALIZED (
        SELECT
            d.*,
            prior.id AS prior_event_id,
            prior.market_price AS prior_market_price,
            prior.high_price AS prior_high_price,
            prior.low_price AS prior_low_price
        FROM day_rows d
        LEFT JOIN LATERAL (
            SELECT event_row.id, event_row.market_price, event_row.high_price, event_row.low_price
            FROM public.card_variant_price_events_v2 event_row
            WHERE event_row.card_variant_id = d.card_variant_id
              AND event_row.condition_id = d.condition_id
              AND event_row.source = d.source
              AND event_row.currency = d.currency
              AND event_row.effective_date < p_market_date
            ORDER BY event_row.effective_date DESC, event_row.id DESC
            LIMIT 1
        ) prior ON true
    )
    DELETE FROM public.card_variant_price_events_v2 event_row
    USING compared c
    WHERE event_row.card_variant_id = c.card_variant_id
      AND event_row.condition_id = c.condition_id
      AND event_row.source = c.source
      AND event_row.currency = c.currency
      AND event_row.effective_date = p_market_date
      AND c.prior_event_id IS NOT NULL
      AND c.market_price IS NOT DISTINCT FROM c.prior_market_price
      AND c.high_price IS NOT DISTINCT FROM c.prior_high_price
      AND c.low_price IS NOT DISTINCT FROM c.prior_low_price;

    GET DIAGNOSTICS v_deleted_events = ROW_COUNT;

    WITH day_rows AS MATERIALIZED (
        SELECT DISTINCT ON (
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN'),
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD')
        )
            observation.id AS source_observation_id,
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN') AS source,
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD') AS currency,
            observation.captured_at AS effective_date,
            observation.market_price,
            observation.high_price,
            observation.low_price,
            observation.created_at AS source_created_at
        FROM public.card_variant_price_observations observation
        JOIN public.card_variants variant ON variant.id = observation.card_variant_id
        JOIN public.cards card ON card.id = variant.card_id
        WHERE card.set_id = p_set_id
          AND observation.captured_at = p_market_date
          AND observation.market_price IS NOT NULL
        ORDER BY
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN'),
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD'),
            observation.created_at DESC,
            observation.id DESC
    ), compared AS MATERIALIZED (
        SELECT
            d.*,
            prior.id AS prior_event_id,
            prior.market_price AS prior_market_price,
            prior.high_price AS prior_high_price,
            prior.low_price AS prior_low_price
        FROM day_rows d
        LEFT JOIN LATERAL (
            SELECT event_row.id, event_row.market_price, event_row.high_price, event_row.low_price
            FROM public.card_variant_price_events_v2 event_row
            WHERE event_row.card_variant_id = d.card_variant_id
              AND event_row.condition_id = d.condition_id
              AND event_row.source = d.source
              AND event_row.currency = d.currency
              AND event_row.effective_date < p_market_date
            ORDER BY event_row.effective_date DESC, event_row.id DESC
            LIMIT 1
        ) prior ON true
    )
    INSERT INTO public.card_variant_price_events_v2 (
        card_variant_id, condition_id, source, currency, effective_date,
        event_type, market_price, high_price, low_price,
        source_observation_id, source_created_at
    )
    SELECT
        c.card_variant_id, c.condition_id, c.source, c.currency, c.effective_date,
        'PRICE', c.market_price, c.high_price, c.low_price,
        c.source_observation_id, c.source_created_at
    FROM compared c
    WHERE c.prior_event_id IS NULL
       OR c.market_price IS DISTINCT FROM c.prior_market_price
       OR c.high_price IS DISTINCT FROM c.prior_high_price
       OR c.low_price IS DISTINCT FROM c.prior_low_price
    ON CONFLICT (card_variant_id, condition_id, source, currency, effective_date)
    DO UPDATE SET
        event_type = EXCLUDED.event_type,
        market_price = EXCLUDED.market_price,
        high_price = EXCLUDED.high_price,
        low_price = EXCLUDED.low_price,
        source_observation_id = EXCLUDED.source_observation_id,
        source_created_at = EXCLUDED.source_created_at;

    GET DIAGNOSTICS v_upserted_events = ROW_COUNT;

    WITH day_rows AS MATERIALIZED (
        SELECT DISTINCT ON (
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN'),
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD')
        )
            observation.id AS last_observation_id,
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN') AS source,
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD') AS currency,
            observation.captured_at AS last_observed_date,
            observation.created_at AS last_observation_created_at
        FROM public.card_variant_price_observations observation
        JOIN public.card_variants variant ON variant.id = observation.card_variant_id
        JOIN public.cards card ON card.id = variant.card_id
        WHERE card.set_id = p_set_id
          AND observation.captured_at = p_market_date
          AND observation.market_price IS NOT NULL
        ORDER BY
            observation.card_variant_id,
            observation.condition_id,
            COALESCE(NULLIF(trim(observation.source), ''), 'UNKNOWN'),
            COALESCE(NULLIF(trim(both '"' from upper(trim(observation.currency))), ''), 'USD'),
            observation.created_at DESC,
            observation.id DESC
    ), resolved AS MATERIALIZED (
        SELECT
            d.*,
            latest_event.id AS event_id,
            latest_event.effective_date,
            latest_event.event_type,
            latest_event.market_price,
            latest_event.high_price,
            latest_event.low_price,
            latest_event.source_observation_id
        FROM day_rows d
        JOIN LATERAL (
            SELECT event_row.*
            FROM public.card_variant_price_events_v2 event_row
            WHERE event_row.card_variant_id = d.card_variant_id
              AND event_row.condition_id = d.condition_id
              AND event_row.source = d.source
              AND event_row.currency = d.currency
              AND event_row.effective_date <= p_market_date
            ORDER BY event_row.effective_date DESC, event_row.id DESC
            LIMIT 1
        ) latest_event ON true
    )
    INSERT INTO public.card_variant_price_current_v2 (
        card_variant_id, condition_id, source, currency,
        event_id, effective_date, state,
        market_price, high_price, low_price,
        source_observation_id,
        last_observed_date, last_observation_id, last_observation_created_at,
        updated_at
    )
    SELECT
        r.card_variant_id, r.condition_id, r.source, r.currency,
        r.event_id, r.effective_date, r.event_type,
        r.market_price, r.high_price, r.low_price,
        r.source_observation_id,
        r.last_observed_date, r.last_observation_id, r.last_observation_created_at,
        now()
    FROM resolved r
    ON CONFLICT (card_variant_id, condition_id, source, currency)
    DO UPDATE SET
        event_id = EXCLUDED.event_id,
        effective_date = EXCLUDED.effective_date,
        state = EXCLUDED.state,
        market_price = EXCLUDED.market_price,
        high_price = EXCLUDED.high_price,
        low_price = EXCLUDED.low_price,
        source_observation_id = EXCLUDED.source_observation_id,
        last_observed_date = EXCLUDED.last_observed_date,
        last_observation_id = EXCLUDED.last_observation_id,
        last_observation_created_at = EXCLUDED.last_observation_created_at,
        updated_at = now()
    WHERE public.card_variant_price_current_v2.last_observed_date IS NULL
       OR EXCLUDED.last_observed_date >= public.card_variant_price_current_v2.last_observed_date;

    GET DIAGNOSTICS v_upserted_current = ROW_COUNT;

    RETURN jsonb_build_object(
        'set_id', p_set_id,
        'market_date', p_market_date,
        'day_rows', v_day_rows,
        'deleted_redundant_events', v_deleted_events,
        'upserted_events', v_upserted_events,
        'upserted_current_rows', v_upserted_current
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.process_price_storage_v2_shadow_queue(
    p_limit integer DEFAULT 2
)
RETURNS jsonb
LANGUAGE plpgsql
SET search_path TO ''
AS $$
DECLARE
    v_job record;
    v_processed integer := 0;
    v_completed integer := 0;
    v_failed integer := 0;
    v_result jsonb;
BEGIN
    IF p_limit IS NULL OR p_limit < 1 OR p_limit > 20 THEN
        RAISE EXCEPTION 'p_limit must be between 1 and 20';
    END IF;

    FOR v_job IN
        SELECT q.id, q.set_id, q.market_date
        FROM public.price_storage_v2_shadow_queue q
        WHERE q.status IN ('pending','failed')
        ORDER BY q.market_date, q.id
        FOR UPDATE SKIP LOCKED
        LIMIT p_limit
    LOOP
        v_processed := v_processed + 1;

        UPDATE public.price_storage_v2_shadow_queue
        SET status = 'processing',
            attempts = attempts + 1,
            started_at = now(),
            completed_at = NULL,
            last_error = NULL,
            updated_at = now()
        WHERE id = v_job.id;

        BEGIN
            v_result := public.sync_price_storage_v2_set_date(v_job.set_id, v_job.market_date);

            UPDATE public.price_storage_v2_shadow_queue
            SET status = 'complete',
                completed_at = now(),
                last_error = NULL,
                updated_at = now()
            WHERE id = v_job.id;
            v_completed := v_completed + 1;
        EXCEPTION WHEN OTHERS THEN
            UPDATE public.price_storage_v2_shadow_queue
            SET status = 'failed',
                completed_at = now(),
                last_error = left(SQLERRM, 2000),
                updated_at = now()
            WHERE id = v_job.id;
            v_failed := v_failed + 1;
        END;
    END LOOP;

    RETURN jsonb_build_object(
        'processed', v_processed,
        'completed', v_completed,
        'failed', v_failed
    );
END;
$$;

REVOKE ALL ON FUNCTION public.enqueue_price_storage_v2_shadow_set_date(uuid, date) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.sync_price_storage_v2_set_date(uuid, date) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.process_price_storage_v2_shadow_queue(integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.enqueue_price_storage_v2_shadow_set_date(uuid, date) TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_price_storage_v2_set_date(uuid, date) TO service_role;
GRANT EXECUTE ON FUNCTION public.process_price_storage_v2_shadow_queue(integer) TO service_role;

COMMENT ON TABLE public.price_storage_v2_shadow_queue IS
'Backend-only queue for post-ingestion Price Storage V2 shadow synchronization. Queueing is intentionally decoupled from the production raw-price write path.';
COMMENT ON FUNCTION public.sync_price_storage_v2_set_date(uuid, date) IS
'Idempotently projects one successfully persisted set/date from legacy raw observations into Price Storage V2. Intended for forward shadow synchronization; historical repairs should use the scoped full rebuild function.';

COMMIT;