"use client";

import PokemonSetMobileHero from "@/components/pokemon/set-page/PokemonSetHero/PokemonSetMobileHero";
import SetPageIcon from "@/components/pokemon/set-page/SetPageIcon";
import RichSetSectionTabs from "./RichSetSectionTabs";

const formatLongDate = (value) => { if (!value) return "—"; const date = new Date(`${String(value).slice(0, 10)}T00:00:00Z`); return Number.isNaN(date.getTime()) ? String(value) : new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" }).format(date); };

export default function RichSetContextChrome({ activeTab, onTabChange, onTabIntent, isTabNavPending, mobileContextHidden, mobileContextRef, mobileHeroModel, pickerOpen, setPickerOpen, onTogglePicker, onSelectTarget, onPickerKeyDown, onTargetIntent, targets, selectedTargetId, pickerDisabled, isDesktop, logoUrl, selectedName, selectedTarget, cardCount, ripPresentation, ripTier, ripRank, ripCohort }) {
  return <div data-set-context-shell className="set-detail-context-shell overflow-visible rounded-xl desk:flex desk:flex-col md:rounded-2xl">
    <div id="set-detail-content" data-set-detail-sticky-tabs data-mobile-set-context-hidden={mobileContextHidden ? "true" : "false"} ref={mobileContextRef} className="set-detail-sticky-tabs max-desk:mt-2 min-h-10 desk:order-2 scroll-mt-24 rounded-b-xl border border-t-0 border-[var(--border-subtle)] bg-[var(--surface-panel)] p-1 shadow-[0_8px_24px_rgba(2,6,23,0.24)] desk:bg-[color:color-mix(in_srgb,var(--surface-panel)_96%,transparent)] desk:backdrop-blur-md md:min-h-11 md:scroll-mt-28 md:rounded-b-2xl" aria-busy={isTabNavPending}>
      <div data-set-sticky-picker data-set-picker className="relative z-30 desk:hidden">
        <PokemonSetMobileHero model={mobileHeroModel} pickerOpen={pickerOpen} onTogglePicker={onTogglePicker} onSelectTarget={onSelectTarget} onPickerKeyDown={onPickerKeyDown} targets={targets} selectedTargetId={selectedTargetId} pickerDisabled={pickerDisabled} listboxId="set-mobile-picker-list" isPickerOwner={!isDesktop} surfaceClassName="rounded-none border-0 bg-transparent px-0 py-0" />
        <span aria-hidden="true" className="mb-0.5 mt-0.5 block h-px bg-[var(--border-subtle)]" />
      </div>
      <RichSetSectionTabs className={`transition-opacity duration-150 ${isTabNavPending ? "opacity-60" : ""}`} value={activeTab} onChange={onTabChange} onOptionIntent={onTabIntent} variant="primary" options={[{ value: "overview", label: "RIP", icon: "gauge", hideIconOnMobile: true }, { value: "market", label: "Market", icon: "trend", hideIconOnMobile: true }, { value: "cards", label: "Cards & Products", mobileLabel: "Cards", icon: "cards", hideIconOnMobile: true }, { value: "pull-rates", label: "Pull Rates", icon: "target", hideIconOnMobile: true }]} />
    </div>
    <section data-set-context-header data-set-picker-open={setPickerOpen ? "true" : "false"} className="set-context-premium page-hero-panel relative min-h-[88px] overflow-visible rounded-t-xl border max-desk:hidden desk:order-1 md:rounded-t-2xl">
      <div className="mx-auto grid min-h-[88px] w-full max-w-[1400px] items-stretch md:grid-cols-[minmax(20rem,2fr)_repeat(3,minmax(8.5rem,1fr))]">
        <div data-set-picker data-compact-set-picker className="relative z-20 flex min-w-0 items-center gap-4 px-4 py-2.5 sm:gap-6 md:gap-7 md:px-5">
          {logoUrl ? <span className="flex h-14 w-24 flex-none items-center justify-center sm:h-16 sm:w-28"><img src={logoUrl} alt="" aria-hidden="true" className="max-h-14 w-auto max-w-24 object-contain opacity-95 sm:max-h-16 sm:max-w-28" loading="lazy" decoding="async" /></span> : null}
          <div className="flex min-w-0 flex-1 items-center"><button type="button" onClick={onTogglePicker} disabled={pickerDisabled} aria-expanded={setPickerOpen} aria-haspopup="listbox" aria-controls="compact-set-picker-list" aria-hidden={isDesktop ? undefined : true} tabIndex={isDesktop ? 0 : -1} className="set-context-identity flex min-h-12 max-w-full items-center gap-2.5 rounded-lg text-left text-lg font-semibold text-[var(--text-primary)] transition-colors hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)] disabled:cursor-not-allowed disabled:opacity-90 md:text-xl" title={targets.length ? "Switch set" : "No sets available"}><span className="min-w-0 py-0.5"><span className="block truncate leading-tight">{selectedName}</span>{selectedTarget?.era ? <span className="mt-1.5 block truncate text-xs font-medium leading-tight tracking-[0.01em] text-[var(--text-secondary)]">{selectedTarget.era}</span> : null}</span><span aria-hidden="true" className="inline-flex h-6 w-6 flex-none items-center justify-center rounded-full border border-[var(--border-subtle)] bg-[var(--surface-page)]/70"><svg viewBox="0 0 20 20" className={`h-4 w-4 text-[var(--text-secondary)] transition-transform ${setPickerOpen ? "rotate-180" : ""}`} fill="currentColor"><path d="M5.23 7.21a.75.75 0 0 1 1.06.02L10 11.12l3.71-3.89a.75.75 0 1 1 1.08 1.04l-4.25 4.45a.75.75 0 0 1-1.08 0L5.21 8.27a.75.75 0 0 1 .02-1.06Z" /></svg></span></button>
            {setPickerOpen ? <div id="compact-set-picker-list" role="listbox" aria-label="Available sets" onKeyDown={onPickerKeyDown} className="index-scrollbar set-dropdown-glass absolute left-0 top-[calc(100%+0.5rem)] z-50 max-h-56 w-full min-w-[16rem] overflow-y-auto rounded-xl p-1.5">{targets.map((target) => { const selected = String(target.target_id) === String(selectedTargetId || ""); return <button key={`compact-set-option:${target.target_type}:${target.target_id}`} type="button" role="option" aria-selected={selected} onMouseEnter={() => onTargetIntent?.(target.target_id)} onFocus={() => onTargetIntent?.(target.target_id)} onClick={() => onSelectTarget(target)} className={`set-dropdown-option flex w-full items-center justify-between gap-2 rounded-lg px-3 py-2 text-left text-sm leading-5 transition-colors ${selected ? "text-[var(--text-primary)]" : "text-[var(--text-secondary)] hover:text-[var(--text-primary)]"}`}><span className="min-w-0 flex-1 truncate whitespace-nowrap">{target.name}</span>{selected ? <span className="shrink-0 text-xs font-medium text-[var(--accent)]">Current</span> : null}</button>; })}</div> : null}
          </div>
        </div>
        <div data-set-context-release-date className="min-w-0 border-t border-[var(--border-subtle)] px-4 py-2.5 md:border-l md:border-t-0"><p className="set-context-eyebrow flex items-center gap-1.5"><SetPageIcon name="calendar" />Release Date</p><p className="mt-2 text-sm font-semibold tabular-nums text-[var(--text-primary)]">{selectedTarget?.release_date || selectedTarget?.releaseDate ? formatLongDate(selectedTarget?.release_date ?? selectedTarget?.releaseDate) : "—"}</p></div>
        <div data-set-context-total-cards className="min-w-0 border-t border-[var(--border-subtle)] px-4 py-2.5 md:border-l md:border-t-0"><p className="set-context-eyebrow flex items-center gap-1.5"><SetPageIcon name="cards" />Total Cards</p><p className="mt-2 text-sm font-semibold tabular-nums text-[var(--text-primary)]">{cardCount > 0 ? Math.round(cardCount).toLocaleString("en-US") : "—"}</p></div>
        <div data-set-context-rip className="min-w-0 border-t border-[var(--border-subtle)] px-4 py-2.5 md:border-l md:border-t-0"><p className="set-context-eyebrow flex items-center gap-1.5"><SetPageIcon name="trophy" />RIP Rank</p><div className="mt-1.5 flex min-w-0 flex-wrap items-center gap-x-2 gap-y-1">{ripTier ? <span data-set-context-rip-tier className="inline-flex flex-none items-center rounded-full border px-2 py-0.5 text-[11px] font-semibold leading-tight" style={ripPresentation.tierPill}>{ripTier} Tier</span> : null}{ripRank !== null ? <span data-set-context-rip-rank className="flex-none text-[11px] font-medium leading-tight tabular-nums text-[var(--text-secondary)]" title={ripCohort === null ? `Rank #${Math.round(ripRank)}` : `Rank #${Math.round(ripRank)} of ${Math.round(ripCohort)} ranked sets`}>#{Math.round(ripRank)}{ripCohort === null ? "" : ` of ${Math.round(ripCohort)}`}</span> : null}</div></div>
      </div>
    </section>
  </div>;
}
