"use client";

import Link from "next/link";
import { startTransition, useEffect, useState } from "react";
import { buildPokemonCardHref } from "@/lib/pokemon/pokemonCardDetailClient";
import { optimizedImageUrl, CARD_ART_WIDTH } from "@/lib/images/remoteImageDelivery.mjs";
import MarketValueChange from "@/components/ui/MarketValueChange";
import { getCardMovement7d } from "@/components/explore/moversTickerSelector.mjs";

const number = (value) => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : null; };
function price(card) { const value = number(card?.marketPrice ?? card?.market_price ?? card?.currentPrice ?? card?.current_price ?? card?.price ?? card?.estimatedMarketPrice ?? card?.estimated_market_price ?? card?.current_near_mint_price ?? card?.currentNearMintPrice ?? card?.price_used ?? card?.priceUsed ?? card?.card_price ?? card?.cardPrice ?? card?.card_market_price ?? card?.cardMarketPrice ?? card?.tcgplayer?.prices?.holofoil?.market ?? card?.tcgplayer?.prices?.reverseHolofoil?.market ?? card?.tcgplayer?.prices?.normal?.market ?? card?.cardmarket?.prices?.averageSellPrice); return value !== null && value > 0 ? value : null; }
function movement(card, windowKey) { const source = windowKey === "7D" ? (getCardMovement7d(card) || card?.deltas?.["7d"] || card?.deltas?.["7D"]) : (card?.deltas?.["30d"] || card?.deltas?.["30D"]); if (!source) return null; return { amount: number(source.amount ?? source.changeAmount ?? source.change_amount), percent: number(source.percent ?? source.changePercent ?? source.change_percent), isPartialWindow: Boolean(source.isPartialWindow ?? source.is_partial_window), windowCoverageDays: number(source.windowCoverageDays ?? source.window_coverage_days) }; }
function Placeholder({ shimmer = false, label = null }) { return <div className={`absolute inset-1 flex flex-col items-center justify-center gap-1.5 rounded-md border border-[rgba(255,255,255,0.05)] ${shimmer ? "animate-pulse bg-[rgba(148,163,184,0.09)]" : "bg-[rgba(148,163,184,0.05)]"}`} aria-hidden={label ? undefined : "true"}><svg viewBox="0 0 24 24" className="h-9 w-9 text-[rgba(148,163,184,0.35)]" fill="none" stroke="currentColor" strokeWidth="1.25" aria-hidden="true"><rect x="5.5" y="3" width="13" height="18" rx="1.8"/><circle cx="12" cy="9.5" r="2.4"/><path d="M8.4 16.6c1-1.7 2.2-2.6 3.6-2.6s2.6.9 3.6 2.6"/></svg>{label ? <span className="px-2 text-center text-[10px] font-medium leading-tight text-[rgba(148,163,184,0.6)]">{label}</span> : null}</div>; }

export default function RichChecklistCardTile({ card, movementWindow = "7D" }) {
  const imageUrl = optimizedImageUrl(card?.imageSmallUrl || card?.imageLargeUrl || null, CARD_ART_WIDTH);
  const name = card?.name || "Unknown card"; const cardNumber = card?.printedNumber || card?.cardNumber || null; const rarity = card?.rarity || null; const subtype = Array.isArray(card?.subtypes) && card.subtypes.length ? card.subtypes.join(" / ") : null;
  const marketPrice = price(card); const delta = movement(card, movementWindow); const hasPrice = marketPrice !== null;
  const [loaded, setLoaded] = useState(false); const [failed, setFailed] = useState(false); const [meta, setMeta] = useState(false);
  useEffect(() => { setLoaded(false); setFailed(false); }, [imageUrl]);
  useEffect(() => { setMeta(false); if (hasPrice) startTransition(() => setMeta(true)); }, [card?.id, marketPrice, delta?.amount, delta?.percent, movementWindow, hasPrice]);
  const href = buildPokemonCardHref(card?.detailSetSlug, card);
  const accessiblePeriod = delta?.isPartialWindow ? (delta.windowCoverageDays === null ? "since the first available observation" : `since the first available observation, covering ${delta.windowCoverageDays} ${delta.windowCoverageDays === 1 ? "day" : "days"}`) : null;
  return <article className="group h-full overflow-hidden rounded-lg border border-[rgba(255,255,255,0.10)] bg-transparent backdrop-blur-none transition-all duration-200 hover:-translate-y-0.5 hover:border-[rgba(94,234,212,0.40)] focus-within:border-[rgba(94,234,212,0.55)]"><Link href={href || "#"} prefetch={false} aria-label={`View ${name} card details`} className="block h-full rounded-lg focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-teal-300"><div className="relative aspect-[3/4] w-full border-b border-[rgba(255,255,255,0.07)] bg-transparent p-1">{imageUrl && !failed ? <>{!loaded ? <Placeholder shimmer /> : null}<img ref={(node) => { if (node?.complete && node.naturalWidth > 0) setLoaded(true); }} src={imageUrl} alt={name} onLoad={() => setLoaded(true)} onError={() => setFailed(true)} className={`h-full w-full object-contain drop-shadow-[0_4px_12px_rgba(2,6,23,0.55)] transition-all duration-300 group-hover:scale-[1.01] ${loaded ? "opacity-100" : "opacity-0"}`} loading="lazy" decoding="async"/></> : <Placeholder label="Image unavailable" />}</div><div className="space-y-1 bg-transparent px-2.5 py-2 [text-shadow:0_1px_3px_rgba(2,6,23,0.9)]"><div className="flex min-w-0 items-start justify-between gap-2"><div className="min-w-0 flex-1"><p className="line-clamp-2 text-[13px] font-semibold leading-snug text-[var(--text-primary)]">{name}</p>{cardNumber ? <p className="truncate text-[11px] text-[var(--text-secondary)]">No. {cardNumber}</p> : null}</div><div className="min-w-[7.5rem] shrink-0 text-right">{meta || !hasPrice ? <MarketValueChange value={marketPrice} changeAmount={delta?.amount} changePercent={delta?.percent} windowLabel={movementWindow} windowLabelPlacement="below" unavailable={!delta} accessiblePeriodLabel={accessiblePeriod} alignment="right" variant="card-tile" accessibleLabel={`${name} market price`} /> : <div className="ml-auto space-y-1" aria-hidden="true"><div className="ml-auto h-3.5 w-12 animate-pulse rounded bg-[rgba(148,163,184,0.12)]"/><div className="ml-auto h-3 w-24 animate-pulse rounded bg-[rgba(148,163,184,0.10)]"/><div className="ml-auto h-2.5 w-6 animate-pulse rounded bg-[rgba(148,163,184,0.08)]"/></div>}</div></div>{rarity || subtype ? <p className="truncate text-[11px] text-[var(--text-secondary)]">{[rarity, subtype].filter(Boolean).join(" · ")}</p> : null}</div></Link></article>;
}
